# Generated by Django 4.2.11 on 2025-11-06 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0007_screener'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomIndicator',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('mode', models.CharField(choices=[('formula', 'Formula'), ('js', 'JavaScript')], default='formula', max_length=16)),
                ('formula', models.TextField(blank=True)),
                ('js_code', models.TextField(blank=True)),
                ('params', models.JSONField(default=list, help_text='Parameter schema array')),
                ('palette', models.JSONField(default=dict, help_text='Color configuration for rendering')),
                ('privacy', models.CharField(choices=[('private', 'Private'), ('unlisted', 'Unlisted'), ('public', 'Public')], default='private', max_length=16)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('ip_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('user_agent', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralTrialEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_number', models.CharField(max_length=32)),
                ('body', models.CharField(max_length=1600)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=10)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=32)),
                ('code_plain', models.CharField(max_length=12)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.IntegerField(default=0)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='membership',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='stockprice',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='stocks_stoc_current_5f7bd2_idx',
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='stocks_stoc_market__da2818_idx',
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='sms_breaking_news',
            field=models.BooleanField(default=False, help_text='SMS for breaking news'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='sms_enabled',
            field=models.BooleanField(default=False, help_text='Enable SMS notifications'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='sms_milestone_alerts',
            field=models.BooleanField(default=False, help_text='SMS for portfolio milestones'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='sms_price_alerts',
            field=models.BooleanField(default=False, help_text='SMS for price alerts'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='sms_verified',
            field=models.BooleanField(default=False, help_text='Phone verified for SMS'),
        ),
        migrations.AddField(
            model_name='stock',
            name='valuation_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['exchange', 'volume'], name='stocks_stoc_exchang_daf84d_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['exchange', 'market_cap'], name='stocks_stoc_exchang_abfb09_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['exchange', 'current_price'], name='stocks_stoc_exchang_37c08c_idx'),
        ),
        migrations.AddIndex(
            model_name='stockprice',
            index=models.Index(fields=['stock', 'timestamp'], name='stocks_stoc_stock_i_63cdc2_idx'),
        ),
        migrations.AddIndex(
            model_name='stockprice',
            index=models.Index(fields=['timestamp'], name='stocks_stoc_timesta_7a363a_idx'),
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.AddField(
            model_name='smsverification',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sms_verification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referraltrialevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='referralclickevent',
            index=models.Index(fields=['code', 'occurred_at'], name='stocks_refe_code_74896d_idx'),
        ),
        migrations.AddIndex(
            model_name='referralclickevent',
            index=models.Index(fields=['ip_hash', 'occurred_at'], name='stocks_refe_ip_hash_3bf123_idx'),
        ),
        migrations.AddField(
            model_name='customindicator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_indicators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='smsverification',
            index=models.Index(fields=['user'], name='stocks_smsv_user_id_a79f24_idx'),
        ),
        migrations.AddIndex(
            model_name='smsverification',
            index=models.Index(fields=['expires_at'], name='stocks_smsv_expires_70ce40_idx'),
        ),
        migrations.AddIndex(
            model_name='smsmessage',
            index=models.Index(fields=['user', '-created_at'], name='stocks_smsm_user_id_f24226_idx'),
        ),
        migrations.AddIndex(
            model_name='smsmessage',
            index=models.Index(fields=['status'], name='stocks_smsm_status_faf670_idx'),
        ),
        migrations.AddIndex(
            model_name='referraltrialevent',
            index=models.Index(fields=['code', 'occurred_at'], name='stocks_refe_code_5746b7_idx'),
        ),
        migrations.AddIndex(
            model_name='referraltrialevent',
            index=models.Index(fields=['user', 'occurred_at'], name='stocks_refe_user_id_f5073f_idx'),
        ),
        migrations.AddIndex(
            model_name='customindicator',
            index=models.Index(fields=['user', '-updated_at'], name='stocks_cust_user_id_75eae4_idx'),
        ),
        migrations.AddIndex(
            model_name='customindicator',
            index=models.Index(fields=['privacy', '-updated_at'], name='stocks_cust_privacy_8976e6_idx'),
        ),
    ]
