# Generated by Django 4.2.25 on 2025-10-26 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0007_screener'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='sms_breaking_news',
            field=models.BooleanField(default=False, help_text='SMS for breaking news'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='sms_enabled',
            field=models.BooleanField(default=False, help_text='Enable SMS notifications'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='sms_milestone_alerts',
            field=models.BooleanField(default=False, help_text='SMS for portfolio milestones'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='sms_price_alerts',
            field=models.BooleanField(default=False, help_text='SMS for price alerts'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='sms_verified',
            field=models.BooleanField(default=False, help_text='Phone verified for SMS'),
        ),
        migrations.AddField(
            model_name='stock',
            name='valuation_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SMSVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=32)),
                ('code_plain', models.CharField(max_length=12)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.IntegerField(default=0)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sms_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='stocks_smsv_user_id_a79f24_idx'), models.Index(fields=['expires_at'], name='stocks_smsv_expires_70ce40_idx')],
            },
        ),
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_number', models.CharField(max_length=32)),
                ('body', models.CharField(max_length=1600)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=10)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='stocks_smsm_user_id_f24226_idx'), models.Index(fields=['status'], name='stocks_smsm_status_faf670_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomIndicator',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('mode', models.CharField(choices=[('formula', 'Formula'), ('js', 'JavaScript')], default='formula', max_length=16)),
                ('formula', models.TextField(blank=True)),
                ('js_code', models.TextField(blank=True)),
                ('params', models.JSONField(default=list, help_text='Parameter schema array')),
                ('palette', models.JSONField(default=dict, help_text='Color configuration for rendering')),
                ('privacy', models.CharField(choices=[('private', 'Private'), ('unlisted', 'Unlisted'), ('public', 'Public')], default='private', max_length=16)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_indicators', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', '-updated_at'], name='stocks_cust_user_id_75eae4_idx'), models.Index(fields=['privacy', '-updated_at'], name='stocks_cust_privacy_8976e6_idx')],
            },
        ),
    ]
