# Generated by Django 4.2.11 on 2025-11-16 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0008_customindicator_referralclickevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenuetracking',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5),
        ),
        migrations.CreateModel(
            name='VisitorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, help_text='Unique session identifier', max_length=64)),
                ('ip_hash', models.CharField(db_index=True, help_text='Hashed IP address for privacy', max_length=64)),
                ('country_code', models.CharField(blank=True, db_index=True, help_text='2-letter country code (US, UK, etc)', max_length=2)),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('checkout_start', 'Checkout Started'), ('purchase_complete', 'Purchase Completed')], db_index=True, default='page_view', max_length=20)),
                ('page_url', models.CharField(blank=True, help_text='Page URL visited', max_length=512)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, help_text='User if logged in', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['session_id', 'event_type'], name='stocks_visi_session_11b1b1_idx'), models.Index(fields=['country_code', 'occurred_at'], name='stocks_visi_country_36d471_idx'), models.Index(fields=['event_type', 'occurred_at'], name='stocks_visi_event_t_4e648f_idx')],
            },
        ),
        migrations.CreateModel(
            name='CheckoutEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('started', 'Checkout Started'), ('payment_info', 'Payment Info Entered'), ('processing', 'Processing Payment'), ('completed', 'Purchase Completed'), ('abandoned', 'Checkout Abandoned')], db_index=True, default='started', max_length=20)),
                ('plan_name', models.CharField(blank=True, help_text='Plan user is purchasing', max_length=100)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Checkout amount in USD', max_digits=10, null=True)),
                ('country_code', models.CharField(blank=True, help_text="User's country", max_length=2)),
                ('referral_code', models.CharField(blank=True, db_index=True, help_text='Referral/discount code used', max_length=50)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['status', 'started_at'], name='stocks_chec_status_9cfcb7_idx'), models.Index(fields=['user', 'started_at'], name='stocks_chec_user_id_8e6359_idx'), models.Index(fields=['country_code', 'started_at'], name='stocks_chec_country_f0eeec_idx'), models.Index(fields=['referral_code', 'started_at'], name='stocks_chec_referra_c45abe_idx')],
            },
        ),
    ]
