# Generated by Django 4.2.26 on 2025-12-01 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0009_alter_revenuetracking_commission_rate_visitorevent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockFundamentals",
            fields=[
                (
                    "stock",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="fundamentals",
                        serialize=False,
                        to="stocks.stock",
                    ),
                ),
                (
                    "pe_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Price to Earnings ratio",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "forward_pe",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Forward P/E ratio",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "peg_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="PEG ratio",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "price_to_sales",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Price to Sales ratio",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "price_to_book",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Price to Book ratio",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "ev_to_revenue",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Enterprise Value to Revenue",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "ev_to_ebitda",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Enterprise Value to EBITDA",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "enterprise_value",
                    models.BigIntegerField(
                        blank=True, help_text="Enterprise Value", null=True
                    ),
                ),
                (
                    "gross_margin",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Gross profit margin",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "operating_margin",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Operating margin",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "profit_margin",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Net profit margin",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "roe",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Return on Equity",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "roa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Return on Assets",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "roic",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Return on Invested Capital",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "revenue_growth_yoy",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="YoY revenue growth",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "revenue_growth_3y",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="3-year revenue CAGR",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "revenue_growth_5y",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="5-year revenue CAGR",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "earnings_growth_yoy",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="YoY earnings growth",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "earnings_growth_5y",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="5-year EPS CAGR",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "fcf_growth_yoy",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="YoY free cash flow growth",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "current_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Current ratio",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "quick_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Quick ratio",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "debt_to_equity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Debt to equity ratio",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "debt_to_assets",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Debt to assets ratio",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "interest_coverage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Interest coverage ratio",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "altman_z_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Altman Z-Score",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "piotroski_f_score",
                    models.IntegerField(
                        blank=True, help_text="Piotroski F-Score (0-9)", null=True
                    ),
                ),
                (
                    "operating_cash_flow",
                    models.BigIntegerField(
                        blank=True, help_text="Operating cash flow", null=True
                    ),
                ),
                (
                    "free_cash_flow",
                    models.BigIntegerField(
                        blank=True, help_text="Free cash flow", null=True
                    ),
                ),
                (
                    "fcf_per_share",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="FCF per share",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "fcf_yield",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="FCF yield",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "cash_conversion",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Cash conversion ratio",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "dividend_yield",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Dividend yield",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "dividend_payout_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Dividend payout ratio",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "years_dividend_growth",
                    models.IntegerField(
                        blank=True,
                        help_text="Consecutive years of dividend growth",
                        null=True,
                    ),
                ),
                (
                    "dcf_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="DCF fair value",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "epv_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="EPV fair value",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "graham_number",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Graham Number",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "peg_fair_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="PEG-based fair value",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "relative_value_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Relative value vs sector",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "valuation_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Composite valuation score (0-100)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "valuation_status",
                    models.CharField(
                        blank=True,
                        help_text="Status: significantly_undervalued, undervalued, fair_value, etc.",
                        max_length=50,
                    ),
                ),
                (
                    "recommendation",
                    models.CharField(
                        blank=True,
                        help_text="STRONG BUY, BUY, HOLD, SELL, STRONG SELL",
                        max_length=20,
                    ),
                ),
                (
                    "confidence",
                    models.CharField(
                        blank=True, help_text="high, medium, low", max_length=10
                    ),
                ),
                (
                    "strength_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Financial strength score (0-100)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "strength_grade",
                    models.CharField(
                        blank=True,
                        help_text="Strength grade: A, B, C, D, F",
                        max_length=2,
                    ),
                ),
                (
                    "sector",
                    models.CharField(
                        blank=True, help_text="Company sector", max_length=100
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True, help_text="Company industry", max_length=100
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "data_quality",
                    models.CharField(
                        default="complete",
                        help_text="Data quality: complete, partial, insufficient",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Stock fundamentals",
            },
        ),
        migrations.RemoveField(
            model_name="visitorevent",
            name="user",
        ),
        migrations.AlterField(
            model_name="revenuetracking",
            name="commission_rate",
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
        ),
        migrations.DeleteModel(
            name="CheckoutEvent",
        ),
        migrations.DeleteModel(
            name="VisitorEvent",
        ),
        migrations.AddIndex(
            model_name="stockfundamentals",
            index=models.Index(
                fields=["valuation_score"], name="stocks_stoc_valuati_ba0763_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockfundamentals",
            index=models.Index(
                fields=["valuation_status"], name="stocks_stoc_valuati_167517_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockfundamentals",
            index=models.Index(
                fields=["strength_score"], name="stocks_stoc_strengt_2fc31f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockfundamentals",
            index=models.Index(fields=["sector"], name="stocks_stoc_sector_a88255_idx"),
        ),
        migrations.AddIndex(
            model_name="stockfundamentals",
            index=models.Index(
                fields=["last_updated"], name="stocks_stoc_last_up_ccd3dd_idx"
            ),
        ),
    ]
