# Generated by Django 4.2.26 on 2025-12-01 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stocks", "0010_stockfundamentals_remove_visitorevent_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaselineStrategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("day_trading", "Day Trading"),
                            ("swing_trading", "Swing Trading"),
                            ("long_term", "Long Term"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "strategy_code",
                    models.TextField(help_text="Python strategy implementation"),
                ),
                (
                    "avg_total_return",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "avg_sharpe_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "avg_max_drawdown",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Baseline strategies",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="ValueHunterWeek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_number", models.IntegerField(help_text="ISO week number")),
                ("year", models.IntegerField()),
                ("week_start", models.DateField(help_text="Monday of the week")),
                ("week_end", models.DateField(help_text="Friday of the week")),
                (
                    "starting_capital",
                    models.DecimalField(
                        decimal_places=2, default=10000.0, max_digits=15
                    ),
                ),
                (
                    "ending_capital",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "weekly_return",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Weekly return percentage",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "cumulative_return",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cumulative return since inception",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "benchmark_return",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "alpha",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Weekly alpha vs benchmark",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-year", "-week_number"],
                "indexes": [
                    models.Index(
                        fields=["-year", "-week_number"],
                        name="stocks_valu_year_e37562_idx",
                    ),
                    models.Index(
                        fields=["status"], name="stocks_valu_status_73af98_idx"
                    ),
                ],
                "unique_together": {("year", "week_number")},
            },
        ),
        migrations.CreateModel(
            name="ValueHunterPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=10)),
                (
                    "valuation_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valuation score at selection",
                        max_digits=5,
                    ),
                ),
                ("rank", models.IntegerField(help_text="Rank in top 10 (1-10)")),
                ("shares", models.DecimalField(decimal_places=4, max_digits=15)),
                ("entry_price", models.DecimalField(decimal_places=4, max_digits=15)),
                (
                    "exit_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "entry_datetime",
                    models.DateTimeField(help_text="Entry time (Monday 9:35 AM ET)"),
                ),
                (
                    "exit_datetime",
                    models.DateTimeField(
                        blank=True, help_text="Exit time (Friday 3:55 PM ET)", null=True
                    ),
                ),
                (
                    "return_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "return_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stocks.stock",
                    ),
                ),
                (
                    "week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="stocks.valuehunterweek",
                    ),
                ),
            ],
            options={
                "ordering": ["week", "rank"],
                "indexes": [
                    models.Index(
                        fields=["week", "rank"], name="stocks_valu_week_id_4279fd_idx"
                    ),
                    models.Index(
                        fields=["symbol"], name="stocks_valu_symbol_5d8a1a_idx"
                    ),
                ],
                "unique_together": {("week", "symbol")},
            },
        ),
        migrations.CreateModel(
            name="BacktestRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Strategy name", max_length=200)),
                (
                    "strategy_text",
                    models.TextField(help_text="Natural language strategy description"),
                ),
                (
                    "generated_code",
                    models.TextField(blank=True, help_text="AI-generated Python code"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("day_trading", "Day Trading"),
                            ("swing_trading", "Swing Trading"),
                            ("long_term", "Long Term"),
                        ],
                        default="day_trading",
                        max_length=20,
                    ),
                ),
                ("symbols", models.JSONField(help_text="List of symbols to test")),
                ("start_date", models.DateField(help_text="Backtest start date")),
                ("end_date", models.DateField(help_text="Backtest end date")),
                (
                    "initial_capital",
                    models.DecimalField(
                        decimal_places=2, default=10000.0, max_digits=15
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "total_return",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total return percentage",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "annualized_return",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "sharpe_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "max_drawdown",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "win_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentage of winning trades",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "profit_factor",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                ("total_trades", models.IntegerField(blank=True, null=True)),
                ("winning_trades", models.IntegerField(blank=True, null=True)),
                ("losing_trades", models.IntegerField(blank=True, null=True)),
                (
                    "composite_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Overall strategy score 0-100",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "trades_data",
                    models.JSONField(
                        blank=True, help_text="Individual trade records", null=True
                    ),
                ),
                (
                    "equity_curve",
                    models.JSONField(
                        blank=True, help_text="Portfolio value over time", null=True
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                (
                    "is_baseline",
                    models.BooleanField(
                        default=False, help_text="Official baseline strategy"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backtest_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="stocks_back_user_id_611aff_idx",
                    ),
                    models.Index(
                        fields=["status"], name="stocks_back_status_393016_idx"
                    ),
                    models.Index(
                        fields=["category", "-composite_score"],
                        name="stocks_back_categor_341f05_idx",
                    ),
                    models.Index(
                        fields=["-composite_score"],
                        name="stocks_back_composi_2d193f_idx",
                    ),
                    models.Index(
                        fields=["is_baseline"], name="stocks_back_is_base_520b37_idx"
                    ),
                ],
            },
        ),
    ]
