# Generated by Django 4.2.11 on 2025-12-19 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_remove_checkoutevent_user_remove_visitorevent_user_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stock',
            name='stocks_stoc_symbol_3e1bfd_idx',
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='idx_change_volume',
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='idx_updated_desc',
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='idx_company_search',
        ),
    ]
