# Generated by Django 4.2.11 on 2025-12-24 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0011_baselinestrategy_valuehunterweek_valuehunterposition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperTradingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Paper Trading Account', max_length=100)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=100000.0, help_text='Starting virtual cash', max_digits=15)),
                ('cash_balance', models.DecimalField(decimal_places=2, default=100000.0, help_text='Current available cash', max_digits=15)),
                ('equity_value', models.DecimalField(decimal_places=2, default=0.0, help_text='Current value of open positions', max_digits=15)),
                ('total_value', models.DecimalField(decimal_places=2, default=100000.0, help_text='Cash + Equity', max_digits=15)),
                ('total_return', models.DecimalField(decimal_places=2, default=0.0, help_text='Total return percentage', max_digits=10)),
                ('total_profit_loss', models.DecimalField(decimal_places=2, default=0.0, help_text='Total P/L in dollars', max_digits=15)),
                ('realized_pl', models.DecimalField(decimal_places=2, default=0.0, help_text='Realized profit/loss from closed trades', max_digits=15)),
                ('unrealized_pl', models.DecimalField(decimal_places=2, default=0.0, help_text='Unrealized profit/loss from open positions', max_digits=15)),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('win_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of winning trades', max_digits=5)),
                ('max_drawdown', models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum peak-to-trough decline', max_digits=10)),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=4, help_text='Risk-adjusted return metric', max_digits=8, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_shorting', models.BooleanField(default=False, help_text='Allow short selling (Pro tier)')),
                ('max_position_size_pct', models.DecimalField(decimal_places=2, default=25.0, help_text='Max position size as % of account', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('last_trade_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaperTradePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('starting_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ending_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('period_return', models.DecimalField(decimal_places=2, help_text='Return percentage for this period', max_digits=10)),
                ('period_pl', models.DecimalField(decimal_places=2, help_text='Profit/loss in dollars for this period', max_digits=15)),
                ('trades_opened', models.IntegerField(default=0)),
                ('trades_closed', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('period_win_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('max_gain', models.DecimalField(decimal_places=2, default=0.0, help_text='Largest single winning trade', max_digits=15)),
                ('max_loss', models.DecimalField(decimal_places=2, default=0.0, help_text='Largest single losing trade', max_digits=15)),
                ('volatility', models.DecimalField(blank=True, decimal_places=4, help_text='Standard deviation of returns', max_digits=8, null=True)),
                ('benchmark_return', models.DecimalField(blank=True, decimal_places=2, help_text='S&P 500 return for same period', max_digits=10, null=True)),
                ('alpha', models.DecimalField(blank=True, decimal_places=2, help_text='Excess return vs benchmark', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='stocks.papertradingaccount')),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='PaperTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('market', 'Market Order'), ('limit', 'Limit Order'), ('stop', 'Stop Order'), ('stop_limit', 'Stop-Limit Order'), ('trailing_stop', 'Trailing Stop'), ('bracket', 'Bracket Order'), ('oco', 'One-Cancels-Other')], default='market', max_length=20)),
                ('side', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], default='long', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('open', 'Open'), ('closed', 'Closed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('shares', models.DecimalField(decimal_places=4, help_text='Number of shares', max_digits=15)),
                ('entry_price', models.DecimalField(blank=True, decimal_places=4, help_text='Actual fill price', max_digits=15, null=True)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=4, help_text='Actual exit price', max_digits=15, null=True)),
                ('current_price', models.DecimalField(blank=True, decimal_places=4, help_text='Current market price for open positions', max_digits=15, null=True)),
                ('limit_price', models.DecimalField(blank=True, decimal_places=4, help_text='Limit price for limit/stop-limit orders', max_digits=15, null=True)),
                ('stop_price', models.DecimalField(blank=True, decimal_places=4, help_text='Stop price for stop/stop-limit orders', max_digits=15, null=True)),
                ('trailing_amount', models.DecimalField(blank=True, decimal_places=4, help_text='Trailing amount for trailing stop (Pro)', max_digits=15, null=True)),
                ('trailing_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Trailing percentage for trailing stop (Pro)', max_digits=5, null=True)),
                ('take_profit_price', models.DecimalField(blank=True, decimal_places=4, help_text='Take profit price for bracket orders', max_digits=15, null=True)),
                ('stop_loss_price', models.DecimalField(blank=True, decimal_places=4, help_text='Stop loss price for bracket orders', max_digits=15, null=True)),
                ('entry_value', models.DecimalField(blank=True, decimal_places=2, help_text='Total entry cost (shares × entry_price)', max_digits=15, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, help_text='Current position value', max_digits=15, null=True)),
                ('exit_value', models.DecimalField(blank=True, decimal_places=2, help_text='Total exit proceeds', max_digits=15, null=True)),
                ('unrealized_pl', models.DecimalField(blank=True, decimal_places=2, help_text='Unrealized profit/loss for open positions', max_digits=15, null=True)),
                ('unrealized_pl_pct', models.DecimalField(blank=True, decimal_places=4, help_text='Unrealized P/L percentage', max_digits=8, null=True)),
                ('realized_pl', models.DecimalField(blank=True, decimal_places=2, help_text='Realized profit/loss for closed positions', max_digits=15, null=True)),
                ('realized_pl_pct', models.DecimalField(blank=True, decimal_places=4, help_text='Realized P/L percentage', max_digits=8, null=True)),
                ('commission', models.DecimalField(decimal_places=2, default=0.0, help_text='Simulated commission fees', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When order was placed')),
                ('filled_at', models.DateTimeField(blank=True, help_text='When order was filled', null=True)),
                ('closed_at', models.DateTimeField(blank=True, help_text='When position was closed', null=True)),
                ('holding_period_days', models.IntegerField(blank=True, help_text='Days held', null=True)),
                ('notes', models.TextField(blank=True, help_text='Trade notes/strategy')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_trades', to='stocks.papertradingaccount')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='papertradingaccount',
            index=models.Index(fields=['user', 'is_active'], name='stocks_pape_user_id_51e5f9_idx'),
        ),
        migrations.AddIndex(
            model_name='papertradingaccount',
            index=models.Index(fields=['-total_return'], name='stocks_pape_total_r_77ec87_idx'),
        ),
        migrations.AddIndex(
            model_name='papertradingaccount',
            index=models.Index(fields=['-created_at'], name='stocks_pape_created_031675_idx'),
        ),
        migrations.AddIndex(
            model_name='papertradeperformance',
            index=models.Index(fields=['account', 'period_type', '-period_start'], name='stocks_pape_account_c88288_idx'),
        ),
        migrations.AddIndex(
            model_name='papertradeperformance',
            index=models.Index(fields=['-period_return'], name='stocks_pape_period__e795d5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='papertradeperformance',
            unique_together={('account', 'period_type', 'period_start')},
        ),
        migrations.AddIndex(
            model_name='papertrade',
            index=models.Index(fields=['account', 'status'], name='stocks_pape_account_0e4fbc_idx'),
        ),
        migrations.AddIndex(
            model_name='papertrade',
            index=models.Index(fields=['stock', '-created_at'], name='stocks_pape_stock_i_e0d42b_idx'),
        ),
        migrations.AddIndex(
            model_name='papertrade',
            index=models.Index(fields=['status', '-created_at'], name='stocks_pape_status_12a83c_idx'),
        ),
        migrations.AddIndex(
            model_name='papertrade',
            index=models.Index(fields=['account', 'stock', 'status'], name='stocks_pape_account_f26365_idx'),
        ),
    ]
