# Generated by Django 4.2.11 on 2025-12-26 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0011_remove_stock_stocks_stoc_symbol_3e1bfd_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Strategy name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Strategy description')),
                ('strategy_type', models.CharField(choices=[('day_trading', 'Day Trading'), ('swing_trading', 'Swing Trading'), ('long_term', 'Long Term'), ('scalping', 'Scalping'), ('arbitrage', 'Arbitrage')], default='swing_trading', max_length=20)),
                ('strategy_code', models.TextField(blank=True, help_text='Strategy implementation code')),
                ('configuration', models.JSONField(default=dict, help_text='Strategy parameters and settings')),
                ('entry_rules', models.JSONField(default=list, help_text='Entry conditions')),
                ('exit_rules', models.JSONField(default=list, help_text='Exit conditions')),
                ('max_position_size', models.DecimalField(decimal_places=2, default=10, help_text='Max position size %', max_digits=5)),
                ('max_portfolio_risk', models.DecimalField(decimal_places=2, default=5, help_text='Max portfolio risk %', max_digits=5)),
                ('stop_loss_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Default stop loss %', max_digits=5, null=True)),
                ('take_profit_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Default take profit %', max_digits=5, null=True)),
                ('annual_return', models.DecimalField(blank=True, decimal_places=2, help_text='Annual return %', max_digits=8, null=True)),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_drawdown', models.DecimalField(blank=True, decimal_places=2, help_text='Max drawdown %', max_digits=5, null=True)),
                ('win_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Win rate %', max_digits=5, null=True)),
                ('profit_factor', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_trades', models.IntegerField(default=0, help_text='Total number of trades')),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('unlisted', 'Unlisted'), ('public', 'Public')], default='private', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured by platform')),
                ('is_verified', models.BooleanField(default=False, help_text='Verified by platform')),
                ('clone_count', models.IntegerField(default=0, help_text='Number of times cloned')),
                ('view_count', models.IntegerField(default=0, help_text='Number of views')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('last_traded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_strategies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StrategyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(decimal_places=1, help_text='Total composite score', max_digits=5)),
                ('performance_score', models.DecimalField(decimal_places=1, help_text='Performance component (30%)', max_digits=5)),
                ('risk_score', models.DecimalField(decimal_places=1, help_text='Risk management component (25%)', max_digits=5)),
                ('consistency_score', models.DecimalField(decimal_places=1, help_text='Consistency component (20%)', max_digits=5)),
                ('efficiency_score', models.DecimalField(decimal_places=1, help_text='Efficiency component (15%)', max_digits=5)),
                ('community_score', models.DecimalField(decimal_places=1, help_text='Community component (10%)', max_digits=5)),
                ('is_sufficient_data', models.BooleanField(default=False, help_text='Has sufficient data for reliable scoring')),
                ('verification_status', models.CharField(default='pending', help_text='Score verification status', max_length=20)),
                ('last_calculated_at', models.DateTimeField(auto_now=True)),
                ('strategy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='stocks.tradingstrategy')),
            ],
        ),
        migrations.CreateModel(
            name='StrategyRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Rating 1-5 stars')),
                ('review', models.TextField(blank=True, help_text='Optional review text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='stocks.tradingstrategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StrategyLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(help_text='Rank position in leaderboard')),
                ('category', models.CharField(choices=[('overall', 'Overall'), ('day_trading', 'Day Trading'), ('swing_trading', 'Swing Trading'), ('long_term', 'Long Term'), ('scalping', 'Scalping'), ('arbitrage', 'Arbitrage')], max_length=20)),
                ('timeframe', models.CharField(choices=[('1d', '1 Day'), ('1w', '1 Week'), ('1m', '1 Month'), ('3m', '3 Months'), ('6m', '6 Months'), ('1y', '1 Year'), ('all', 'All Time')], max_length=10)),
                ('score', models.DecimalField(decimal_places=1, help_text='Score for this timeframe/category', max_digits=5)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.tradingstrategy')),
            ],
            options={
                'ordering': ['category', 'timeframe', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='StrategyClone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloned_at', models.DateTimeField(auto_now_add=True)),
                ('cloned_strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloned_from', to='stocks.tradingstrategy')),
                ('original_strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clones_made', to='stocks.tradingstrategy')),
                ('user', models.ForeignKey(help_text='User who cloned the strategy', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cloned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tradingstrategy',
            index=models.Index(fields=['user', '-created_at'], name='stocks_trad_user_id_eb208d_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingstrategy',
            index=models.Index(fields=['strategy_type', 'visibility'], name='stocks_trad_strateg_20bee6_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingstrategy',
            index=models.Index(fields=['is_featured', 'is_verified'], name='stocks_trad_is_feat_f05261_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingstrategy',
            index=models.Index(fields=['annual_return'], name='stocks_trad_annual__2c8cba_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingstrategy',
            index=models.Index(fields=['clone_count'], name='stocks_trad_clone_c_09780e_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyscore',
            index=models.Index(fields=['total_score'], name='stocks_stra_total_s_e7eeaf_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyscore',
            index=models.Index(fields=['is_sufficient_data'], name='stocks_stra_is_suff_5dd7ca_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyrating',
            index=models.Index(fields=['strategy', '-created_at'], name='stocks_stra_strateg_d8761e_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyrating',
            index=models.Index(fields=['rating'], name='stocks_stra_rating_b12831_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='strategyrating',
            unique_together={('strategy', 'user')},
        ),
        migrations.AddIndex(
            model_name='strategyleaderboard',
            index=models.Index(fields=['category', 'timeframe', 'rank'], name='stocks_stra_categor_d1c53a_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyleaderboard',
            index=models.Index(fields=['strategy', 'calculated_at'], name='stocks_stra_strateg_86656f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='strategyleaderboard',
            unique_together={('strategy', 'category', 'timeframe')},
        ),
        migrations.AddIndex(
            model_name='strategyclone',
            index=models.Index(fields=['original_strategy', '-cloned_at'], name='stocks_stra_origina_c8e4a6_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyclone',
            index=models.Index(fields=['user', '-cloned_at'], name='stocks_stra_user_id_3b6c8d_idx'),
        ),
    ]
