# Generated by Django 4.2.11 on 2025-12-24 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0012_papertradingaccount_papertradeperformance_papertrade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextBeltConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.URLField(default='http://localhost:8080/text', help_text='TextBelt API endpoint URL')),
                ('api_key', models.CharField(blank=True, help_text='Optional API key (for paid plans)', max_length=200)),
                ('is_self_hosted', models.BooleanField(default=True, help_text='Whether using self-hosted TextBelt')),
                ('max_retries', models.IntegerField(default=3)),
                ('retry_delay_seconds', models.IntegerField(default=60)),
                ('max_sms_per_minute', models.IntegerField(default=10, help_text='Rate limit for SMS sending')),
                ('total_sent', models.IntegerField(default=0)),
                ('total_failed', models.IntegerField(default=0)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TextBelt Configuration',
                'verbose_name_plural': 'TextBelt Configuration',
            },
        ),
        migrations.CreateModel(
            name='SMSAlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Alert name/description', max_length=200)),
                ('is_multi_condition', models.BooleanField(default=False, help_text='Whether this is a multi-condition alert (Pro tier)')),
                ('condition_operator', models.CharField(choices=[('and', 'AND - All conditions must be true'), ('or', 'OR - Any condition can be true')], default='and', help_text='How to combine multiple conditions (Pro tier)', max_length=10)),
                ('phone_number', models.CharField(help_text='Phone number for SMS (E.164 format)', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('trigger_count', models.IntegerField(default=0, help_text='Number of times this alert has triggered')),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('is_one_time', models.BooleanField(default=False, help_text='Deactivate after first trigger')),
                ('max_triggers_per_day', models.IntegerField(default=10, help_text='Maximum triggers per day (prevent spam)')),
                ('webhook_url', models.URLField(blank=True, help_text='Optional webhook to call when alert triggers')),
                ('webhook_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(blank=True, help_text='Specific stock (leave blank for watchlist alerts)', null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_alerts', to=settings.AUTH_USER_MODEL)),
                ('watchlist', models.ForeignKey(blank=True, help_text='Apply alert to all stocks in watchlist', null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.userwatchlist')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSAlertQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_limit', models.IntegerField(default=50, help_text='Monthly SMS limit')),
                ('current_usage', models.IntegerField(default=0, help_text='SMS sent this month')),
                ('last_reset_at', models.DateTimeField(auto_now_add=True, help_text='Last monthly reset')),
                ('total_sent', models.IntegerField(default=0, help_text='Total SMS sent all-time')),
                ('is_blocked', models.BooleanField(default=False, help_text='Block SMS if quota exceeded or abuse detected')),
                ('block_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sms_quota', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'SMS Alert Quotas',
            },
        ),
        migrations.CreateModel(
            name='SMSAlertHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='SMS message content')),
                ('phone_number', models.CharField(max_length=20)),
                ('trigger_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('trigger_volume', models.BigIntegerField(blank=True, null=True)),
                ('condition_values', models.JSONField(blank=True, help_text='Values of all conditions when triggered', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('retry', 'Retrying')], default='pending', max_length=20)),
                ('textbelt_id', models.CharField(blank=True, help_text='TextBelt message ID', max_length=100)),
                ('textbelt_quota', models.IntegerField(blank=True, help_text='Remaining TextBelt quota', null=True)),
                ('delivery_attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('error_message', models.TextField(blank=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('webhook_sent', models.BooleanField(default=False)),
                ('webhook_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('alert_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='stocks.smsalertrule')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.stock')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSAlertCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_type', models.CharField(choices=[('price_above', 'Price Above'), ('price_below', 'Price Below'), ('price_crosses_above', 'Price Crosses Above'), ('price_crosses_below', 'Price Crosses Below'), ('volume_surge', 'Volume Surge'), ('volume_above', 'Volume Above'), ('price_change_percent', 'Price Change %'), ('rsi_above', 'RSI Above'), ('rsi_below', 'RSI Below'), ('macd_cross_bullish', 'MACD Bullish Cross'), ('macd_cross_bearish', 'MACD Bearish Cross'), ('sma_cross_above', 'SMA Cross Above'), ('sma_cross_below', 'SMA Cross Below'), ('gap_up', 'Gap Up %'), ('gap_down', 'Gap Down %')], max_length=30)),
                ('target_value', models.DecimalField(decimal_places=4, help_text='Target value for comparison', max_digits=15)),
                ('indicator_period', models.IntegerField(blank=True, help_text='Period for indicator calculation (e.g., 14 for RSI)', null=True)),
                ('comparison_period', models.IntegerField(blank=True, help_text='Second period for cross comparisons (e.g., SMA 50 vs SMA 200)', null=True)),
                ('last_met_at', models.DateTimeField(blank=True, help_text='When this condition was last met', null=True)),
                ('previous_value', models.DecimalField(blank=True, decimal_places=4, help_text='Previous value for cross detection', max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='stocks.smsalertrule')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='smsalertrule',
            index=models.Index(fields=['user', 'is_active'], name='stocks_smsa_user_id_162a39_idx'),
        ),
        migrations.AddIndex(
            model_name='smsalertrule',
            index=models.Index(fields=['stock', 'is_active'], name='stocks_smsa_stock_i_402175_idx'),
        ),
        migrations.AddIndex(
            model_name='smsalertrule',
            index=models.Index(fields=['watchlist', 'is_active'], name='stocks_smsa_watchli_adb909_idx'),
        ),
        migrations.AddIndex(
            model_name='smsalertrule',
            index=models.Index(fields=['-last_checked_at'], name='stocks_smsa_last_ch_4d28ef_idx'),
        ),
        migrations.AddIndex(
            model_name='smsalerthistory',
            index=models.Index(fields=['alert_rule', '-created_at'], name='stocks_smsa_alert_r_c2214f_idx'),
        ),
        migrations.AddIndex(
            model_name='smsalerthistory',
            index=models.Index(fields=['status', '-created_at'], name='stocks_smsa_status_ba3a7a_idx'),
        ),
        migrations.AddIndex(
            model_name='smsalerthistory',
            index=models.Index(fields=['phone_number', '-created_at'], name='stocks_smsa_phone_n_69c7fa_idx'),
        ),
        migrations.AddIndex(
            model_name='smsalertcondition',
            index=models.Index(fields=['alert_rule', 'condition_type'], name='stocks_smsa_alert_r_16b64f_idx'),
        ),
    ]
