# Generated by Django 4.2.11 on 2025-12-24 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0013_textbeltconfig_smsalertrule_smsalertquota_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFactorAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='Whether 2FA is enabled')),
                ('phone_number', models.CharField(help_text='Phone number for 2FA (E.164 format)', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, help_text='When phone was verified', null=True)),
                ('backup_codes', models.JSONField(default=list, help_text='List of backup codes (hashed)')),
                ('backup_codes_count', models.IntegerField(default=10, help_text='Number of unused backup codes')),
                ('require_on_login', models.BooleanField(default=True, help_text='Require 2FA on every login')),
                ('require_on_sensitive', models.BooleanField(default=True, help_text='Require 2FA for sensitive operations')),
                ('trusted_devices_enabled', models.BooleanField(default=True, help_text='Allow trusted device feature')),
                ('total_verifications', models.IntegerField(default=0)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_failed_at', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='twofa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Two-Factor Authentication',
                'verbose_name_plural': 'Two-Factor Authentication',
            },
        ),
        migrations.CreateModel(
            name='TwoFactorCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='6-digit verification code', max_length=10)),
                ('code_type', models.CharField(choices=[('login', 'Login Verification'), ('enable', 'Enable 2FA'), ('disable', 'Disable 2FA'), ('sensitive', 'Sensitive Operation'), ('recovery', 'Account Recovery')], default='login', max_length=20)),
                ('expires_at', models.DateTimeField(help_text='Code expiration time')),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('sms_sent', models.BooleanField(default=False)),
                ('sms_sent_at', models.DateTimeField(blank=True, null=True)),
                ('textbelt_id', models.CharField(blank=True, max_length=100)),
                ('verification_attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('twofa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='stocks.twofactorauth')),
                ('user', models.ForeignKey(help_text='Redundant for quick queries', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_used', '-created_at'], name='stocks_twof_user_id_572d7a_idx'), models.Index(fields=['code', 'is_used'], name='stocks_twof_code_8fa424_idx'), models.Index(fields=['-expires_at'], name='stocks_twof_expires_7510be_idx')],
            },
        ),
        migrations.CreateModel(
            name='TwoFactorAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('enabled', '2FA Enabled'), ('disabled', '2FA Disabled'), ('code_sent', 'Code Sent'), ('code_verified', 'Code Verified'), ('code_failed', 'Code Verification Failed'), ('backup_used', 'Backup Code Used'), ('backup_generated', 'Backup Codes Generated'), ('device_trusted', 'Device Trusted'), ('device_revoked', 'Device Trust Revoked'), ('account_locked', 'Account Locked'), ('account_unlocked', 'Account Unlocked')], max_length=30)),
                ('event_description', models.TextField(blank=True)),
                ('success', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('twofa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.twofactorauth')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twofa_audit_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='stocks_twof_user_id_66ddf1_idx'), models.Index(fields=['event_type', '-created_at'], name='stocks_twof_event_t_a27161_idx'), models.Index(fields=['success', '-created_at'], name='stocks_twof_success_786e71_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(help_text='User-friendly device name', max_length=200)),
                ('device_fingerprint', models.CharField(help_text='Hashed device fingerprint', max_length=64, unique=True)),
                ('user_agent', models.TextField(help_text='Browser user agent')),
                ('ip_address', models.GenericIPAddressField()),
                ('location', models.CharField(blank=True, help_text='Approximate location', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('trust_expires_at', models.DateTimeField(help_text='When trust expires (default 30 days)')),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('total_uses', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('twofa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to='stocks.twofactorauth')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_used_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='stocks_trus_user_id_8e5761_idx'), models.Index(fields=['device_fingerprint'], name='stocks_trus_device__f4ee68_idx'), models.Index(fields=['-trust_expires_at'], name='stocks_trus_trust_e_ccb6c6_idx')],
            },
        ),
    ]
