# Generated by Django 4.2.11 on 2025-12-24 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0014_twofactorauth_twofactorcode_twofactorauditlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionsChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(help_text='Date of this chain snapshot')),
                ('snapshot_time', models.DateTimeField(help_text='Exact time of snapshot')),
                ('underlying_price', models.DecimalField(decimal_places=4, help_text='Stock price at snapshot time', max_digits=15)),
                ('data_source', models.CharField(default='yfinance', help_text='Source of options data', max_length=50)),
                ('total_contracts', models.IntegerField(default=0, help_text='Total number of contracts')),
                ('expirations_count', models.IntegerField(default=0, help_text='Number of expiration dates')),
                ('is_current', models.BooleanField(default=True, help_text='Whether this is the most recent chain')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options_chains', to='stocks.stock')),
            ],
            options={
                'ordering': ['-snapshot_time'],
            },
        ),
        migrations.CreateModel(
            name='OptionsContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_symbol', models.CharField(help_text='OCC option symbol', max_length=50, unique=True)),
                ('contract_type', models.CharField(choices=[('call', 'Call'), ('put', 'Put')], max_length=10)),
                ('strike', models.DecimalField(decimal_places=4, help_text='Strike price', max_digits=15)),
                ('expiration', models.DateField(help_text='Expiration date')),
                ('dte', models.IntegerField(help_text='Days to expiration')),
                ('last_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('bid', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('ask', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('mark', models.DecimalField(blank=True, decimal_places=4, help_text='Mid price (bid + ask) / 2', max_digits=15, null=True)),
                ('volume', models.BigIntegerField(blank=True, help_text='Trading volume', null=True)),
                ('open_interest', models.BigIntegerField(blank=True, null=True)),
                ('implied_volatility', models.DecimalField(blank=True, decimal_places=6, help_text='IV as decimal (e.g., 0.25 = 25%)', max_digits=8, null=True)),
                ('delta', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('gamma', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('theta', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('vega', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('rho', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('in_the_money', models.BooleanField(default=False)),
                ('intrinsic_value', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('extrinsic_value', models.DecimalField(decimal_places=4, default=0, help_text='Time value', max_digits=15)),
                ('break_even', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('probability_itm', models.DecimalField(blank=True, decimal_places=2, help_text='Probability of being in-the-money at expiration', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='stocks.optionschain')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
            ],
            options={
                'ordering': ['expiration', 'strike'],
            },
        ),
        migrations.CreateModel(
            name='OptionsWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Options Watchlist', max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options_watchlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OptionsAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_call_volume', models.BigIntegerField(default=0)),
                ('total_put_volume', models.BigIntegerField(default=0)),
                ('put_call_volume_ratio', models.DecimalField(decimal_places=4, default=0, help_text='Put volume / Call volume', max_digits=8)),
                ('total_call_oi', models.BigIntegerField(default=0, help_text='Total call open interest')),
                ('total_put_oi', models.BigIntegerField(default=0, help_text='Total put open interest')),
                ('put_call_oi_ratio', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('avg_call_iv', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('avg_put_iv', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('iv_30_day', models.DecimalField(blank=True, decimal_places=6, help_text='30-day implied volatility', max_digits=8, null=True)),
                ('iv_rank', models.DecimalField(blank=True, decimal_places=2, help_text='IV Rank (0-100)', max_digits=5, null=True)),
                ('iv_percentile', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('most_active_call_strike', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('most_active_put_strike', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('unusual_call_volume', models.BooleanField(default=False)),
                ('unusual_put_volume', models.BooleanField(default=False)),
                ('iv_spike', models.BooleanField(default=False, help_text='Significant IV increase')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options_analytics', to='stocks.stock')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ImpliedVolatilitySurface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('snapshot_time', models.DateTimeField()),
                ('underlying_price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('surface_data', models.JSONField(help_text='IV surface grid data')),
                ('avg_iv', models.DecimalField(decimal_places=6, help_text='Average IV across surface', max_digits=8)),
                ('min_iv', models.DecimalField(decimal_places=6, help_text='Minimum IV', max_digits=8)),
                ('max_iv', models.DecimalField(decimal_places=6, help_text='Maximum IV', max_digits=8)),
                ('atm_iv', models.DecimalField(blank=True, decimal_places=6, help_text='At-the-money IV', max_digits=8, null=True)),
                ('put_call_iv_ratio', models.DecimalField(blank=True, decimal_places=4, help_text='Ratio of put IV to call IV', max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iv_surfaces', to='stocks.stock')),
            ],
            options={
                'ordering': ['-snapshot_time'],
            },
        ),
        migrations.CreateModel(
            name='OptionsWatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_price', models.DecimalField(decimal_places=4, help_text='Contract price when added', max_digits=15)),
                ('added_iv', models.DecimalField(blank=True, decimal_places=6, help_text='IV when added', max_digits=8, null=True)),
                ('target_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('alert_on_volume', models.BooleanField(default=False)),
                ('alert_on_iv_change', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.optionscontract')),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stocks.optionswatchlist')),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('watchlist', 'contract')},
            },
        ),
        migrations.CreateModel(
            name='OptionsScreenerResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screener_type', models.CharField(choices=[('unusual_volume', 'Unusual Volume'), ('high_iv', 'High Implied Volatility'), ('iv_rank_high', 'IV Rank > 80%'), ('cheap_options', 'Low Premium Options'), ('high_gamma', 'High Gamma'), ('earnings_plays', 'Earnings Plays')], max_length=30)),
                ('scan_date', models.DateField()),
                ('scan_time', models.DateTimeField()),
                ('trigger_metrics', models.JSONField(default=dict, help_text='Metrics that caused this to appear in screener')),
                ('score', models.DecimalField(decimal_places=2, help_text='Screener relevance score', max_digits=5)),
                ('rank', models.IntegerField(help_text='Rank within this screener type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.optionscontract')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options_screener_results', to='stocks.stock')),
            ],
            options={
                'ordering': ['-scan_time', '-score'],
                'indexes': [models.Index(fields=['screener_type', '-scan_time'], name='stocks_opti_screene_c212a8_idx'), models.Index(fields=['stock', 'screener_type'], name='stocks_opti_stock_i_d2bf2d_idx'), models.Index(fields=['-score'], name='stocks_opti_score_80a45b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='optionscontract',
            index=models.Index(fields=['chain', 'contract_type', 'expiration'], name='stocks_opti_chain_i_1d4456_idx'),
        ),
        migrations.AddIndex(
            model_name='optionscontract',
            index=models.Index(fields=['stock', 'expiration', 'strike'], name='stocks_opti_stock_i_596fa1_idx'),
        ),
        migrations.AddIndex(
            model_name='optionscontract',
            index=models.Index(fields=['contract_symbol'], name='stocks_opti_contrac_c09801_idx'),
        ),
        migrations.AddIndex(
            model_name='optionscontract',
            index=models.Index(fields=['expiration', 'strike'], name='stocks_opti_expirat_9c699e_idx'),
        ),
        migrations.AddIndex(
            model_name='optionschain',
            index=models.Index(fields=['stock', '-snapshot_time'], name='stocks_opti_stock_i_c899aa_idx'),
        ),
        migrations.AddIndex(
            model_name='optionschain',
            index=models.Index(fields=['stock', 'is_current'], name='stocks_opti_stock_i_6a83ef_idx'),
        ),
        migrations.AddIndex(
            model_name='optionschain',
            index=models.Index(fields=['snapshot_date'], name='stocks_opti_snapsho_fe461a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='optionschain',
            unique_together={('stock', 'snapshot_time')},
        ),
        migrations.AddIndex(
            model_name='optionsanalytics',
            index=models.Index(fields=['stock', '-date'], name='stocks_opti_stock_i_72f897_idx'),
        ),
        migrations.AddIndex(
            model_name='optionsanalytics',
            index=models.Index(fields=['-put_call_volume_ratio'], name='stocks_opti_put_cal_26558d_idx'),
        ),
        migrations.AddIndex(
            model_name='optionsanalytics',
            index=models.Index(fields=['-iv_rank'], name='stocks_opti_iv_rank_8fa706_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='optionsanalytics',
            unique_together={('stock', 'date')},
        ),
        migrations.AddIndex(
            model_name='impliedvolatilitysurface',
            index=models.Index(fields=['stock', '-snapshot_time'], name='stocks_impl_stock_i_0cbebc_idx'),
        ),
        migrations.AddIndex(
            model_name='impliedvolatilitysurface',
            index=models.Index(fields=['snapshot_date'], name='stocks_impl_snapsho_39970c_idx'),
        ),
    ]
