# Generated by Django 4.2.11 on 2025-12-24 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0015_optionschain_optionscontract_optionswatchlist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Source name (e.g., Reuters, Bloomberg)', max_length=100, unique=True)),
                ('source_type', models.CharField(choices=[('rss', 'RSS Feed'), ('api', 'REST API'), ('scraper', 'Web Scraper')], max_length=20)),
                ('base_url', models.URLField(help_text='Base URL for the source')),
                ('api_key_required', models.BooleanField(default=False)),
                ('api_key', models.CharField(blank=True, help_text='Encrypted API key', max_length=255)),
                ('scraping_rules', models.JSONField(blank=True, default=dict, help_text='CSS selectors and extraction rules')),
                ('reliability_score', models.DecimalField(decimal_places=2, default=1.0, help_text='0.0-1.0 reliability rating', max_digits=3)),
                ('requests_per_hour', models.IntegerField(default=100)),
                ('last_request_at', models.DateTimeField(blank=True, null=True)),
                ('total_articles_fetched', models.IntegerField(default=0)),
                ('total_fetch_errors', models.IntegerField(default=0)),
                ('last_successful_fetch', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_premium', models.BooleanField(default=False, help_text='Requires Pro subscription')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled_categories', models.JSONField(default=list, help_text='List of enabled news categories')),
                ('min_sentiment_score', models.DecimalField(decimal_places=4, default=-1.0, help_text='Filter out articles below this score', max_digits=5)),
                ('exclude_neutral', models.BooleanField(default=False)),
                ('email_notifications', models.BooleanField(default=False)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('notification_frequency', models.CharField(choices=[('realtime', 'Real-time'), ('hourly', 'Hourly Digest'), ('daily', 'Daily Digest')], default='realtime', max_length=20)),
                ('alert_on_very_positive', models.BooleanField(default=True)),
                ('alert_on_very_negative', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('followed_sources', models.ManyToManyField(blank=True, related_name='followers', to='stocks.newssource')),
                ('followed_stocks', models.ManyToManyField(blank=True, related_name='news_followers', to='stocks.stock')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='news_feed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, help_text='External ID from source', max_length=255)),
                ('url', models.URLField(help_text='Article URL', unique=True)),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField(blank=True, help_text='Article summary/snippet')),
                ('content', models.TextField(blank=True, help_text='Full article content')),
                ('author', models.CharField(blank=True, max_length=200)),
                ('published_at', models.DateTimeField(help_text='Original publication time')),
                ('mentioned_tickers', models.JSONField(default=list, help_text='List of ticker symbols mentioned')),
                ('category', models.CharField(blank=True, help_text='earnings, merger, lawsuit, etc.', max_length=50)),
                ('tags', models.JSONField(default=list, help_text='Article tags/keywords')),
                ('view_count', models.IntegerField(default=0)),
                ('click_count', models.IntegerField(default=0)),
                ('is_processed', models.BooleanField(default=False, help_text='Whether sentiment analysis is complete')),
                ('processing_errors', models.TextField(blank=True)),
                ('content_hash', models.CharField(db_index=True, help_text='SHA-256 hash for duplicate detection', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='stocks.newssource')),
                ('stocks', models.ManyToManyField(blank=True, related_name='news_articles', to='stocks.stock')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('breaking', 'Breaking News'), ('sentiment_spike', 'Sentiment Spike'), ('sentiment_drop', 'Sentiment Drop'), ('high_volume', 'High Article Volume'), ('keyword_match', 'Keyword Match')], max_length=30)),
                ('message', models.TextField(help_text='Alert message text')),
                ('sentiment_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('trigger_data', models.JSONField(default=dict, help_text='Additional data about what triggered the alert')),
                ('is_read', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('sms_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.newsarticle')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_alerts', to='stocks.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SentimentTimeseries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.CharField(choices=[('1h', '1 Hour'), ('4h', '4 Hours'), ('1d', '1 Day'), ('1w', '1 Week')], max_length=10)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('avg_sentiment_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('weighted_sentiment', models.DecimalField(decimal_places=4, help_text='Weighted by source reliability', max_digits=5)),
                ('total_articles', models.IntegerField(default=0)),
                ('positive_articles', models.IntegerField(default=0)),
                ('negative_articles', models.IntegerField(default=0)),
                ('neutral_articles', models.IntegerField(default=0)),
                ('sentiment_std_dev', models.DecimalField(blank=True, decimal_places=4, help_text='Standard deviation of sentiment scores', max_digits=5, null=True)),
                ('article_volume_change', models.DecimalField(blank=True, decimal_places=2, help_text='% change in article volume vs previous period', max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_timeseries', to='stocks.stock')),
            ],
            options={
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['stock', 'interval', '-period_start'], name='stocks_sent_stock_i_583002_idx')],
                'unique_together': {('stock', 'interval', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='SentimentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment_label', models.CharField(choices=[('very_positive', 'Very Positive'), ('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative'), ('very_negative', 'Very Negative')], max_length=20)),
                ('sentiment_score', models.DecimalField(decimal_places=4, help_text='Score from -1.0 (negative) to +1.0 (positive)', max_digits=5)),
                ('confidence', models.DecimalField(decimal_places=4, help_text='Confidence in analysis (0.0-1.0)', max_digits=5)),
                ('positive_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('negative_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('neutral_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('analysis_engine', models.CharField(choices=[('vader', 'VADER (NLTK)'), ('textblob', 'TextBlob'), ('transformers', 'HuggingFace Transformers'), ('finbert', 'FinBERT (Financial)')], default='vader', max_length=30)),
                ('engine_version', models.CharField(blank=True, max_length=20)),
                ('aspect_sentiments', models.JSONField(blank=True, default=dict, help_text='Sentiment for specific aspects')),
                ('entities_mentioned', models.JSONField(blank=True, default=list, help_text='Named entities (people, companies, etc.)')),
                ('key_phrases', models.JSONField(blank=True, default=list, help_text='Important phrases extracted')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiments', to='stocks.newsarticle')),
                ('stock', models.ForeignKey(blank=True, help_text='Stock-specific sentiment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_sentiments', to='stocks.stock')),
            ],
            options={
                'ordering': ['-analyzed_at'],
                'indexes': [models.Index(fields=['stock', '-analyzed_at'], name='stocks_sent_stock_i_2598b4_idx'), models.Index(fields=['sentiment_label', '-analyzed_at'], name='stocks_sent_sentime_e46dcb_idx')],
                'unique_together': {('article', 'stock', 'analysis_engine')},
            },
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['-published_at', 'is_processed'], name='stocks_news_publish_fac52f_idx'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['content_hash'], name='stocks_news_content_1c63ec_idx'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['source', '-published_at'], name='stocks_news_source__664c7f_idx'),
        ),
        migrations.AddIndex(
            model_name='newsalert',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='stocks_news_user_id_7c6596_idx'),
        ),
        migrations.AddIndex(
            model_name='newsalert',
            index=models.Index(fields=['stock', '-created_at'], name='stocks_news_stock_i_7037a9_idx'),
        ),
    ]
