# Generated by Django 4.2.11 on 2025-12-24 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0016_news_sentiment_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Strategy name', max_length=200)),
                ('description', models.TextField(help_text='Strategy description and methodology')),
                ('strategy_type', models.CharField(choices=[('momentum', 'Momentum'), ('mean_reversion', 'Mean Reversion'), ('breakout', 'Breakout'), ('swing', 'Swing Trading'), ('day_trading', 'Day Trading'), ('options', 'Options Strategy'), ('custom', 'Custom')], default='custom', max_length=30)),
                ('strategy_code', models.TextField(blank=True, help_text='Python strategy code (optional)')),
                ('configuration', models.JSONField(default=dict, help_text='Strategy parameters and settings')),
                ('entry_rules', models.JSONField(default=list, help_text='Entry condition rules')),
                ('exit_rules', models.JSONField(default=list, help_text='Exit condition rules')),
                ('max_position_size', models.DecimalField(decimal_places=2, default=10.0, help_text='Max % of portfolio per position', max_digits=5)),
                ('max_portfolio_risk', models.DecimalField(decimal_places=2, default=2.0, help_text='Max % portfolio risk per trade', max_digits=5)),
                ('stop_loss_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Default stop loss %', max_digits=5, null=True)),
                ('take_profit_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Default take profit %', max_digits=5, null=True)),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('unlisted', 'Unlisted (link only)'), ('public', 'Public')], default='private', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured on leaderboard')),
                ('is_verified', models.BooleanField(default=False, help_text='Verified by admin/algo')),
                ('clone_count', models.IntegerField(default=0, help_text='Number of times cloned')),
                ('view_count', models.IntegerField(default=0)),
                ('annual_return', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('max_drawdown', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('win_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('profit_factor', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('backtesting', 'Backtesting'), ('paper_trading', 'Paper Trading'), ('live', 'Live Trading'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_traded_at', models.DateTimeField(blank=True, null=True)),
                ('paper_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategies', to='stocks.papertradingaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_strategies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StrategyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_score', models.DecimalField(decimal_places=2, default=0, help_text='Performance metrics (30% weight)', max_digits=5)),
                ('risk_score', models.DecimalField(decimal_places=2, default=0, help_text='Risk-adjusted metrics (25% weight)', max_digits=5)),
                ('consistency_score', models.DecimalField(decimal_places=2, default=0, help_text='Win rate & stability (20% weight)', max_digits=5)),
                ('efficiency_score', models.DecimalField(decimal_places=2, default=0, help_text='Trade efficiency (15% weight)', max_digits=5)),
                ('community_score', models.DecimalField(decimal_places=2, default=0, help_text='Ratings & clones (10% weight)', max_digits=5)),
                ('total_score', models.DecimalField(decimal_places=2, default=0, help_text='Weighted composite score', max_digits=5)),
                ('score_breakdown', models.JSONField(default=dict, help_text='Detailed score calculations')),
                ('min_trades_threshold', models.IntegerField(default=30, help_text='Minimum trades for valid score')),
                ('is_sufficient_data', models.BooleanField(default=False, help_text='Has enough trades for scoring')),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Verification'), ('verified', 'Verified'), ('flagged', 'Flagged for Review')], default='unverified', max_length=20)),
                ('last_calculated_at', models.DateTimeField(auto_now=True)),
                ('calculation_engine_version', models.CharField(default='v1.0', max_length=20)),
                ('strategy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='stocks.tradingstrategy')),
            ],
            options={
                'ordering': ['-total_score'],
            },
        ),
        migrations.CreateModel(
            name='StrategyRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='1-5 stars')),
                ('review', models.TextField(blank=True, help_text='Optional review text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='stocks.tradingstrategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StrategyLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('all_time', 'All Time')], max_length=20)),
                ('category', models.CharField(choices=[('overall', 'Overall'), ('momentum', 'Momentum Strategies'), ('mean_reversion', 'Mean Reversion'), ('breakout', 'Breakout'), ('swing', 'Swing Trading'), ('day_trading', 'Day Trading'), ('options', 'Options'), ('rookies', 'Rookie Strategies (<90 days)')], max_length=30)),
                ('rank', models.IntegerField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('snapshot_data', models.JSONField(default=dict, help_text='Performance metrics at snapshot time')),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='stocks.tradingstrategy')),
            ],
            options={
                'ordering': ['category', 'timeframe', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='StrategyClone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customizations', models.JSONField(default=dict, help_text='Changes made from original')),
                ('is_modified', models.BooleanField(default=False)),
                ('cloned_at', models.DateTimeField(auto_now_add=True)),
                ('cloned_strategy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clone_source', to='stocks.tradingstrategy')),
                ('original_strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clones', to='stocks.tradingstrategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloned_strategies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cloned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tradingstrategy',
            index=models.Index(fields=['user', '-created_at'], name='stocks_trad_user_id_eb208d_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingstrategy',
            index=models.Index(fields=['visibility', 'is_featured'], name='stocks_trad_visibil_dd726f_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingstrategy',
            index=models.Index(fields=['strategy_type', '-annual_return'], name='stocks_trad_strateg_d96c8d_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingstrategy',
            index=models.Index(fields=['-clone_count'], name='stocks_trad_clone_c_c7f2c9_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyscore',
            index=models.Index(fields=['-total_score'], name='stocks_stra_total_s_89150a_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyscore',
            index=models.Index(fields=['is_sufficient_data', '-total_score'], name='stocks_stra_is_suff_0ed831_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyrating',
            index=models.Index(fields=['strategy', '-created_at'], name='stocks_stra_strateg_d8761e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='strategyrating',
            unique_together={('strategy', 'user')},
        ),
        migrations.AddIndex(
            model_name='strategyleaderboard',
            index=models.Index(fields=['category', 'timeframe', 'rank'], name='stocks_stra_categor_d1c53a_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyleaderboard',
            index=models.Index(fields=['-calculated_at'], name='stocks_stra_calcula_0acdf7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='strategyleaderboard',
            unique_together={('strategy', 'timeframe', 'category')},
        ),
        migrations.AddIndex(
            model_name='strategyclone',
            index=models.Index(fields=['original_strategy', '-cloned_at'], name='stocks_stra_origina_c8e4a6_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyclone',
            index=models.Index(fields=['user', '-cloned_at'], name='stocks_stra_user_id_3b6c8d_idx'),
        ),
    ]
