# Generated by Django 4.2.11 on 2025-12-25 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0017_strategy_ranking_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureWalkthrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('trigger_type', models.CharField(choices=[('on_visit', 'On Page Visit'), ('on_first_visit', 'On First Visit Only'), ('manual', 'Manual Trigger'), ('feature_release', 'New Feature Release')], default='on_first_visit', max_length=20)),
                ('target_url', models.CharField(help_text='URL pattern where walkthrough appears', max_length=200)),
                ('steps', models.JSONField(default=list, help_text='Array of walkthrough steps with selectors and text')),
                ('is_active', models.BooleanField(default=True)),
                ('required_tier', models.CharField(choices=[('all', 'All Users'), ('free', 'Free Tier'), ('basic', 'Basic Tier'), ('pro', 'Pro Tier'), ('enterprise', 'Enterprise Tier')], default='all', max_length=20)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority walkthroughs shown first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', 'feature_name'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_name', models.CharField(help_text="Indicator name (e.g., 'RSI', 'MACD')", max_length=100, unique=True)),
                ('full_name', models.CharField(help_text='Full indicator name', max_length=200)),
                ('category', models.CharField(choices=[('trend', 'Trend Indicators'), ('momentum', 'Momentum Indicators'), ('volatility', 'Volatility Indicators'), ('volume', 'Volume Indicators'), ('support_resistance', 'Support/Resistance')], max_length=30)),
                ('short_description', models.CharField(help_text='Tooltip text (1-2 sentences)', max_length=200)),
                ('detailed_explanation', models.TextField(help_text='Comprehensive explanation')),
                ('how_to_use', models.TextField(help_text='How to interpret and use this indicator')),
                ('common_mistakes', models.TextField(blank=True, help_text='Common mistakes to avoid')),
                ('formula', models.TextField(blank=True, help_text='Mathematical formula')),
                ('calculation_example', models.TextField(blank=True, help_text='Step-by-step calculation example')),
                ('default_parameters', models.JSONField(default=dict, help_text='Default parameter values')),
                ('parameter_explanations', models.JSONField(default=dict, help_text='Explanation of each parameter')),
                ('example_chart_url', models.URLField(blank=True, help_text='Example chart showing indicator')),
                ('video_tutorial_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'indicator_name'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBaseArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('article_type', models.CharField(choices=[('faq', 'FAQ'), ('howto', 'How-To Guide'), ('troubleshooting', 'Troubleshooting'), ('feature_guide', 'Feature Guide'), ('api_docs', 'API Documentation'), ('best_practices', 'Best Practices')], max_length=20)),
                ('summary', models.CharField(help_text='Short summary for search results', max_length=300)),
                ('content', models.TextField(help_text='Full article content (Markdown supported)')),
                ('category', models.CharField(help_text='Main category', max_length=50)),
                ('tags', models.JSONField(default=list, help_text='Array of tags for filtering')),
                ('search_keywords', models.TextField(blank=True, help_text='Additional keywords for search')),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('view_count', models.IntegerField(default=0)),
                ('helpful_count', models.IntegerField(default=0, help_text='Users who found this helpful')),
                ('not_helpful_count', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured in knowledge base home')),
                ('last_reviewed_at', models.DateTimeField(blank=True, help_text='Last content review date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', '-view_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Learning path title', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=200, unique=True)),
                ('description', models.TextField(help_text='Path overview and goals')),
                ('category', models.CharField(choices=[('onboarding', 'Platform Onboarding'), ('technical_analysis', 'Technical Analysis'), ('fundamental_analysis', 'Fundamental Analysis'), ('options_trading', 'Options Trading'), ('paper_trading', 'Paper Trading'), ('risk_management', 'Risk Management'), ('strategy_development', 'Strategy Development'), ('news_sentiment', 'News & Sentiment')], max_length=30)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20)),
                ('cover_image_url', models.URLField(blank=True, help_text='Cover image URL')),
                ('estimated_duration_minutes', models.IntegerField(help_text='Total estimated completion time')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_published', models.BooleanField(default=True)),
                ('is_required_for_onboarding', models.BooleanField(default=False, help_text='Required for new users')),
                ('required_tier', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(help_text='Lesson overview')),
                ('content_type', models.CharField(choices=[('text', 'Text/Article'), ('video', 'Video'), ('interactive', 'Interactive Demo'), ('quiz', 'Quiz'), ('exercise', 'Hands-on Exercise')], default='text', max_length=20)),
                ('content', models.TextField(help_text='Lesson content (Markdown supported)')),
                ('video_url', models.URLField(blank=True, help_text='Video URL if content_type is video')),
                ('example_code', models.TextField(blank=True, help_text='Example code snippets')),
                ('interactive_demo_url', models.URLField(blank=True, help_text='Interactive demo link')),
                ('order', models.IntegerField(default=0)),
                ('estimated_duration_minutes', models.IntegerField(default=5)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20)),
                ('quiz_questions', models.JSONField(blank=True, default=list, help_text='Quiz questions for quiz lessons')),
                ('exercise_instructions', models.TextField(blank=True, help_text='Exercise instructions')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='stocks.learningpath')),
            ],
            options={
                'ordering': ['learning_path', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UserWalkthroughProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False, help_text='User dismissed without completing')),
                ('current_step', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walkthrough_progress', to=settings.AUTH_USER_MODEL)),
                ('walkthrough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='stocks.featurewalkthrough')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_percentage', models.IntegerField(default=0, help_text='0-100')),
                ('time_spent_seconds', models.IntegerField(default=0, help_text='Time spent on lesson')),
                ('quiz_score', models.DecimalField(blank=True, decimal_places=2, help_text='Quiz score percentage', max_digits=5, null=True)),
                ('quiz_attempts', models.IntegerField(default=0)),
                ('quiz_answers', models.JSONField(blank=True, default=dict, help_text="User's quiz answers")),
                ('exercise_completed', models.BooleanField(default=False)),
                ('exercise_feedback', models.TextField(blank=True, help_text='Feedback on exercise')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='stocks.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserKBFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_helpful', models.BooleanField(help_text='Did user find this helpful?')),
                ('comment', models.TextField(blank=True, help_text='Optional feedback comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='stocks.knowledgebasearticle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kb_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='learningpath',
            index=models.Index(fields=['category', 'difficulty'], name='stocks_lear_categor_af9b26_idx'),
        ),
        migrations.AddIndex(
            model_name='learningpath',
            index=models.Index(fields=['is_published', 'order'], name='stocks_lear_is_publ_50e23b_idx'),
        ),
        migrations.AddField(
            model_name='knowledgebasearticle',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kb_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgebasearticle',
            name='related_articles',
            field=models.ManyToManyField(blank=True, to='stocks.knowledgebasearticle'),
        ),
        migrations.AddField(
            model_name='knowledgebasearticle',
            name='related_indicators',
            field=models.ManyToManyField(blank=True, related_name='kb_articles', to='stocks.indicatorexplanation'),
        ),
        migrations.AddField(
            model_name='knowledgebasearticle',
            name='related_lessons',
            field=models.ManyToManyField(blank=True, related_name='related_kb_articles', to='stocks.lesson'),
        ),
        migrations.AddField(
            model_name='indicatorexplanation',
            name='related_indicators',
            field=models.ManyToManyField(blank=True, to='stocks.indicatorexplanation'),
        ),
        migrations.AddField(
            model_name='indicatorexplanation',
            name='related_lessons',
            field=models.ManyToManyField(blank=True, related_name='explained_indicators', to='stocks.lesson'),
        ),
        migrations.AddIndex(
            model_name='featurewalkthrough',
            index=models.Index(fields=['is_active', '-priority'], name='stocks_feat_is_acti_4065a5_idx'),
        ),
        migrations.AddIndex(
            model_name='featurewalkthrough',
            index=models.Index(fields=['trigger_type'], name='stocks_feat_trigger_261de9_idx'),
        ),
        migrations.AddIndex(
            model_name='userwalkthroughprogress',
            index=models.Index(fields=['user', 'is_completed'], name='stocks_user_user_id_98ecdc_idx'),
        ),
        migrations.AddIndex(
            model_name='userwalkthroughprogress',
            index=models.Index(fields=['walkthrough', '-started_at'], name='stocks_user_walkthr_9ba76d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userwalkthroughprogress',
            unique_together={('user', 'walkthrough')},
        ),
        migrations.AddIndex(
            model_name='userlessonprogress',
            index=models.Index(fields=['user', 'is_completed'], name='stocks_user_user_id_52c5a1_idx'),
        ),
        migrations.AddIndex(
            model_name='userlessonprogress',
            index=models.Index(fields=['lesson', '-completed_at'], name='stocks_user_lesson__4151bf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userlessonprogress',
            unique_together={('user', 'lesson')},
        ),
        migrations.AddIndex(
            model_name='userkbfeedback',
            index=models.Index(fields=['article', '-created_at'], name='stocks_user_article_552f6b_idx'),
        ),
        migrations.AddIndex(
            model_name='userkbfeedback',
            index=models.Index(fields=['user', '-created_at'], name='stocks_user_user_id_091fa7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userkbfeedback',
            unique_together={('article', 'user')},
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['learning_path', 'order'], name='stocks_less_learnin_bbe10c_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['content_type'], name='stocks_less_content_ec4219_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('learning_path', 'slug')},
        ),
        migrations.AddIndex(
            model_name='knowledgebasearticle',
            index=models.Index(fields=['article_type', 'is_published'], name='stocks_know_article_4471de_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebasearticle',
            index=models.Index(fields=['category', '-view_count'], name='stocks_know_categor_7dd089_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebasearticle',
            index=models.Index(fields=['slug'], name='stocks_know_slug_de1e81_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebasearticle',
            index=models.Index(fields=['-created_at'], name='stocks_know_created_cfff55_idx'),
        ),
        migrations.AddIndex(
            model_name='indicatorexplanation',
            index=models.Index(fields=['category'], name='stocks_indi_categor_7476bd_idx'),
        ),
        migrations.AddIndex(
            model_name='indicatorexplanation',
            index=models.Index(fields=['indicator_name'], name='stocks_indi_indicat_6bbda2_idx'),
        ),
    ]
