# Generated by Django 4.2.11 on 2025-12-25 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0019_alerttemplate_alter_customindicator_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemHealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('database', 'Database Connection'), ('redis', 'Redis Cache'), ('api', 'External API'), ('disk_space', 'Disk Space'), ('memory', 'Memory Usage'), ('celery', 'Celery Workers')], max_length=50)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('unhealthy', 'Unhealthy')], max_length=20)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('details', models.JSONField(default=dict, help_text='Check-specific details')),
                ('error_message', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['check_type', '-checked_at'], name='stocks_syst_check_t_be316d_idx'), models.Index(fields=['status', '-checked_at'], name='stocks_syst_status_0b081f_idx')],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Feature flag key', max_length=100, unique=True)),
                ('description', models.TextField(help_text='What this flag controls')),
                ('is_enabled', models.BooleanField(default=False)),
                ('rollout_strategy', models.CharField(choices=[('all', 'All Users'), ('percentage', 'Percentage Rollout'), ('whitelist', 'Whitelist Only'), ('tier_based', 'Tier-Based')], default='all', max_length=20)),
                ('rollout_percentage', models.IntegerField(default=0, help_text='Percentage of users (0-100)')),
                ('whitelisted_users', models.JSONField(default=list, help_text='User IDs with access')),
                ('tier_requirement', models.CharField(blank=True, help_text='Required tier (basic, pro, etc.)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_feature_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DatabaseMigrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('migration_name', models.CharField(max_length=200)),
                ('applied', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('execution_time_seconds', models.FloatField(blank=True, null=True)),
                ('had_errors', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('was_rolled_back', models.BooleanField(default=False)),
                ('rolled_back_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-applied_at'],
                'indexes': [models.Index(fields=['applied', '-applied_at'], name='stocks_data_applied_3e38b6_idx'), models.Index(fields=['had_errors'], name='stocks_data_had_err_e779d1_idx')],
                'unique_together': {('app_label', 'migration_name')},
            },
        ),
        migrations.CreateModel(
            name='UserDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Dashboard name', max_length=100)),
                ('layout', models.JSONField(default=dict, help_text='Dashboard layout configuration (widgets, positions, sizes)')),
                ('is_default', models.BooleanField(default=False, help_text='Default dashboard for user')),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public (template)'), ('shared', 'Shared with specific users')], default='private', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-updated_at'],
                'indexes': [models.Index(fields=['user', '-updated_at'], name='stocks_user_user_id_b3e7f0_idx'), models.Index(fields=['visibility', '-updated_at'], name='stocks_user_visibil_e6baa9_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login_success', 'Login Success'), ('login_failure', 'Login Failure'), ('password_change', 'Password Change'), ('email_change', 'Email Change'), ('api_key_created', 'API Key Created'), ('api_key_revoked', 'API Key Revoked'), ('permission_change', 'Permission Change'), ('data_export', 'Data Export'), ('suspicious_activity', 'Suspicious Activity')], max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('endpoint', models.CharField(blank=True, max_length=200)),
                ('details', models.JSONField(default=dict, help_text='Additional event context')),
                ('was_blocked', models.BooleanField(default=False, help_text='Was the action blocked?')),
                ('action_taken', models.TextField(blank=True, help_text='Automated response taken')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['user', '-occurred_at'], name='stocks_secu_user_id_9480a0_idx'), models.Index(fields=['event_type', '-occurred_at'], name='stocks_secu_event_t_9bc2a2_idx'), models.Index(fields=['severity', '-occurred_at'], name='stocks_secu_severit_5d35bd_idx'), models.Index(fields=['was_blocked', '-occurred_at'], name='stocks_secu_was_blo_7d43b2_idx')],
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('api_response_time', 'API Response Time'), ('database_query_time', 'Database Query Time'), ('page_load_time', 'Page Load Time'), ('websocket_latency', 'WebSocket Latency'), ('cache_hit_rate', 'Cache Hit Rate')], max_length=50)),
                ('endpoint', models.CharField(blank=True, help_text='API endpoint or page path', max_length=200)),
                ('value', models.FloatField(help_text='Metric value (ms, %, etc.)')),
                ('unit', models.CharField(default='ms', help_text='Unit of measurement', max_length=20)),
                ('request_data', models.JSONField(blank=True, default=dict, help_text='Request context for debugging')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['metric_type', '-recorded_at'], name='stocks_perf_metric__09ac47_idx'), models.Index(fields=['endpoint', '-recorded_at'], name='stocks_perf_endpoin_62b11b_idx')],
            },
        ),
        migrations.CreateModel(
            name='NavigationAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, help_text='User session identifier', max_length=64)),
                ('from_page', models.CharField(max_length=200)),
                ('to_page', models.CharField(max_length=200)),
                ('action', models.CharField(blank=True, help_text='Button/link clicked', max_length=100)),
                ('time_on_page', models.IntegerField(help_text='Seconds spent on page')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navigation_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['session_id', '-timestamp'], name='stocks_navi_session_2434e1_idx'), models.Index(fields=['from_page', '-timestamp'], name='stocks_navi_from_pa_ae934a_idx'), models.Index(fields=['to_page', '-timestamp'], name='stocks_navi_to_page_e728dc_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeploymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Version/tag deployed', max_length=50)),
                ('environment', models.CharField(help_text='production, staging, etc.', max_length=20)),
                ('commit_hash', models.CharField(blank=True, help_text='Git commit hash', max_length=40)),
                ('release_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('success', 'Success'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back')], default='pending', max_length=20)),
                ('error_log', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('deployed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['environment', '-started_at'], name='stocks_depl_environ_3623e9_idx'), models.Index(fields=['status', '-started_at'], name='stocks_depl_status_3e2d26_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChartPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('chart_type', models.CharField(help_text='candlestick, line, area, etc.', max_length=50)),
                ('timeframe', models.CharField(help_text='1m, 5m, 1h, 1d, etc.', max_length=20)),
                ('indicators', models.JSONField(default=list, help_text='List of indicators with parameters')),
                ('drawing_tools', models.JSONField(default=list, help_text='Saved drawings/annotations')),
                ('color_scheme', models.JSONField(default=dict, help_text='Custom color configuration')),
                ('is_public', models.BooleanField(default=False, help_text='Share as public template')),
                ('clone_count', models.IntegerField(default=0, help_text='Times cloned by other users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', '-updated_at'], name='stocks_char_user_id_681c49_idx'), models.Index(fields=['is_public', '-clone_count'], name='stocks_char_is_publ_e03a14_idx')],
            },
        ),
    ]
