# Generated by Django 4.2.11 on 2026-01-05 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0020_systemhealthcheck_featureflag_databasemigrationlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_id', models.CharField(help_text='Achievement type ID', max_length=50)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('backtest_id', models.IntegerField(blank=True, help_text='Backtest that triggered this achievement', null=True)),
                ('shared_on_social', models.BooleanField(default=False, help_text='Whether user shared this achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-unlocked_at'],
                'unique_together': {('user', 'achievement_id')},
            },
        ),
    ]
