# Generated by Django 4.2.27 on 2026-01-06 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0024_shared_resource_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeJournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('symbol', models.CharField(db_index=True, max_length=16)),
                ('type', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], default='long', max_length=10)),
                ('entry_price', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('shares', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('strategy', models.CharField(blank=True, max_length=200)),
                ('setup', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('emotions', models.TextField(blank=True)),
                ('lessons', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('open', 'Open'), ('win', 'Win'), ('loss', 'Loss'), ('breakeven', 'Breakeven')], db_index=True, default='open', max_length=12)),
                ('screenshot_url', models.URLField(blank=True)),
                ('pnl', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('pnl_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='sharedresourcelink',
            new_name='stocks_shar_resourc_6ed5d7_idx',
            old_name='stocks_share_resource_type_slug_idx',
        ),
        migrations.RenameIndex(
            model_name='sharedresourcelink',
            new_name='stocks_shar_created_1741d4_idx',
            old_name='stocks_share_created_by_created_at_idx',
        ),
        migrations.AddField(
            model_name='tradejournalentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_journal_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='tradejournalentry',
            index=models.Index(fields=['user', '-date'], name='stocks_trad_user_id_89649d_idx'),
        ),
        migrations.AddIndex(
            model_name='tradejournalentry',
            index=models.Index(fields=['user', 'symbol'], name='stocks_trad_user_id_464ab1_idx'),
        ),
    ]
