# Generated by Django 4.2.27 on 2026-01-06 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0025_tradejournalentry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('export_type', models.CharField(choices=[('stocks', 'Stocks'), ('portfolio', 'Portfolio'), ('watchlist', 'Watchlist'), ('custom_report', 'Custom Report')], default='portfolio', max_length=32)),
                ('format', models.CharField(choices=[('csv', 'CSV')], default='csv', max_length=16)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=16)),
                ('time', models.CharField(default='09:00', max_length=10)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('enabled', models.BooleanField(default=True)),
                ('retention_days', models.IntegerField(default=30)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('sms_recipients', models.CharField(blank=True, max_length=200)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('run_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='stocks_user_user_id_504a92_idx'), models.Index(fields=['user', 'enabled'], name='stocks_user_user_id_903c7a_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('stocks', 'Stocks'), ('portfolio', 'Portfolio'), ('watchlist', 'Watchlist'), ('custom_report', 'Custom Report')], max_length=32)),
                ('format', models.CharField(choices=[('csv', 'CSV')], default='csv', max_length=16)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('processing', 'Processing'), ('failed', 'Failed')], default='processing', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('content_type', models.CharField(default='text/csv', max_length=100)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('content_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('download_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='stocks_user_user_id_180357_idx'), models.Index(fields=['user', 'type'], name='stocks_user_user_id_b7fac7_idx')],
            },
        ),
    ]
