# Generated by Django 4.2.27 on 2026-01-06 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0026_userexportschedule_userexportjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_tickers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-created_at'], name='stocks_favo_user_id_625c95_idx'), models.Index(fields=['user', 'ticker'], name='stocks_favo_user_id_270ae9_idx')],
                'unique_together': {('user', 'ticker')},
            },
        ),
    ]
