@echo off
setlocal ENABLEDELAYEDEXPANSION

REM Secure XAMPP Database Setup for Stock Scanner
REM Usage: setup_xampp_db_secure.bat [DB_NAME] [DB_USER] [DB_PASSWORD] [MYSQL_ROOT_PASSWORD]
REM If not provided, defaults are used and root is assumed to have no password.

echo ========================================
echo Secure XAMPP Database Setup
echo ========================================

REM Defaults
set DB_NAME=%~1
if "%DB_NAME%"=="" set DB_NAME=stockscanner

set DB_USER=%~2
if "%DB_USER%"=="" set DB_USER=stockscanner_user

set DB_PASSWORD=%~3
if "%DB_PASSWORD%"=="" set DB_PASSWORD=StockScanner_2025!

set MYSQL_ROOT_PASSWORD=%~4

REM Paths
set SCRIPT_DIR=%~dp0
set XAMPP_PATH=C:\xampp
set XAMPP_MYSQL_PATH=%XAMPP_PATH%\mysql\bin
set MYSQL_EXE=%XAMPP_MYSQL_PATH%\mysql.exe

echo [INFO] Using settings:
echo   DB_NAME     = %DB_NAME%
echo   DB_USER     = %DB_USER%
echo   DB_PASSWORD = ********
echo   XAMPP PATH  = %XAMPP_PATH%

REM Validate mysql.exe exists
if not exist "%MYSQL_EXE%" (
  echo [ERROR] Cannot find MySQL at %MYSQL_EXE%
  echo Ensure XAMPP is installed at C:\xampp and MySQL component is present.
  exit /b 1
)

REM Build root password flag if provided (arg or env)
set ROOT_FLAG=
if not "%MYSQL_ROOT_PASSWORD%"=="" set ROOT_FLAG=-p%MYSQL_ROOT_PASSWORD%

REM Test root connection
echo [STEP] Testing MySQL root connection...
"%MYSQL_EXE%" -u root %ROOT_FLAG% -e "SELECT VERSION();" >nul 2>&1
if errorlevel 1 (
  echo [ERROR] Could not connect to MySQL as root. If your root has a password, run:
  echo   setup_xampp_db_secure.bat %DB_NAME% %DB_USER% %DB_PASSWORD% ^<MYSQL_ROOT_PASSWORD^>
  exit /b 1
)
echo [OK] Root connection successful

REM Create database and user
echo [STEP] Creating database and user...
"%MYSQL_EXE%" -u root %ROOT_FLAG% -e "^
CREATE DATABASE IF NOT EXISTS `%DB_NAME%` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;^
CREATE USER IF NOT EXISTS '%DB_USER%'@'localhost' IDENTIFIED BY '%DB_PASSWORD%';^
GRANT ALL PRIVILEGES ON `%DB_NAME%`.* TO '%DB_USER%'@'localhost';^
FLUSH PRIVILEGES;"
if errorlevel 1 (
  echo [ERROR] Failed to create database/user or grant privileges.
  exit /b 1
)
echo [OK] Database and user configured

REM Write .env file for Django settings
echo [STEP] Writing .env configuration...
(
  echo # Generated by setup_xampp_db_secure.bat
  echo DEBUG=False
  echo DJANGO_SETTINGS_MODULE=stockscanner_django.settings
  echo DB_ENGINE=django.db.backends.mysql
  echo DB_NAME=%DB_NAME%
  echo DB_USER=%DB_USER%
  echo DB_PASSWORD=%DB_PASSWORD%
  echo DB_HOST=localhost
  echo DB_PORT=3306
) > "%SCRIPT_DIR%\.env"
if errorlevel 1 (
  echo [ERROR] Could not write .env at %SCRIPT_DIR%\.env
  exit /b 1
)
echo [OK] .env written to %SCRIPT_DIR%\.env

REM Show next steps
echo.
echo ========================================
echo Setup complete
echo ========================================
echo - Database: %DB_NAME%
echo - User: %DB_USER%
echo - Password: [hidden]
echo.
echo Next steps:
echo   1. Ensure XAMPP MySQL is running (via XAMPP Control Panel)
echo   2. From this folder, run:  python create_database.py  ^(creates DB if needed and runs migrations^)
echo   3. Start server:          python manage.py runserver
echo.
echo Note: You can re-run this script with custom credentials:
echo   setup_xampp_db_secure.bat mydb myuser "MyStrongP@ss" my_root_password

endlocal
exit /b 0