# Generated by Django 4.2.11 on 2025-08-24 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0003_userwatchlist_userprofile_userportfolio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(help_text='Unique invoice identifier', max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10)),
                ('description', models.CharField(help_text='Payment description', max_length=200)),
                ('status', models.CharField(default='Paid', help_text='Payment status', max_length=50)),
                ('payment_method', models.CharField(default='Credit Card', help_text='Payment method used', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('message', models.TextField(help_text='Notification message')),
                ('notification_type', models.CharField(default='general', help_text='Type of notification', max_length=50)),
                ('is_read', models.BooleanField(default=False, help_text='Whether notification has been read')),
                ('metadata', models.TextField(blank=True, help_text='Additional notification data as JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, help_text='When notification was read', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_alerts', models.BooleanField(default=True, help_text='Price movement alerts')),
                ('volume_alerts', models.BooleanField(default=True, help_text='Volume spike alerts')),
                ('market_hours', models.BooleanField(default=False, help_text='Market hours notifications')),
                ('daily_summary', models.BooleanField(default=True, help_text='Daily portfolio summary')),
                ('weekly_report', models.BooleanField(default=True, help_text='Weekly performance report')),
                ('milestone_alerts', models.BooleanField(default=True, help_text='Portfolio milestone alerts')),
                ('breaking_news', models.BooleanField(default=True, help_text='Breaking market news')),
                ('earnings_alerts', models.BooleanField(default=False, help_text='Earnings announcement alerts')),
                ('analyst_ratings', models.BooleanField(default=False, help_text='Analyst rating changes')),
                ('login_alerts', models.BooleanField(default=True, help_text='Login attempt notifications')),
                ('billing_updates', models.BooleanField(default=True, help_text='Billing and payment updates')),
                ('plan_updates', models.BooleanField(default=True, help_text='Plan change notifications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Usage date')),
                ('api_calls', models.IntegerField(default=0, help_text='Number of API calls made')),
                ('requests', models.IntegerField(default=0, help_text='Total requests made')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='stock',
            name='price_change',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Price change amount', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='price_change_percent',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Price change percentage', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='api_calls_limit',
            field=models.IntegerField(default=100, help_text='API calls limit per month'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='billing_address',
            field=models.TextField(blank=True, help_text='Billing address as JSON'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='billing_cycle',
            field=models.CharField(default='monthly', help_text='Billing cycle (monthly/yearly)', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='card_last_four',
            field=models.CharField(blank=True, help_text='Last 4 digits of payment card', max_length=4),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='card_type',
            field=models.CharField(blank=True, help_text='Type of payment card (Visa, MasterCard, etc.)', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.CharField(blank=True, help_text='User company', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Whether user has premium subscription'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='next_billing_date',
            field=models.DateTimeField(blank=True, help_text='Next billing date', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='payment_updated_at',
            field=models.DateTimeField(blank=True, help_text='When payment method was last updated', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='User phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='plan_changed_at',
            field=models.DateTimeField(blank=True, help_text='When plan was last changed', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='plan_name',
            field=models.CharField(default='Free', help_text='Display name of current plan', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='plan_type',
            field=models.CharField(default='free', help_text='Current subscription plan', max_length=20),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['last_updated'], name='stocks_stoc_last_up_3b4825_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['change_percent'], name='stocks_stoc_change__8293ce_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['exchange'], name='stocks_stoc_exchang_2c4de0_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['pe_ratio'], name='stocks_stoc_pe_rati_b7cd7c_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['price_change_today'], name='stocks_stoc_price_c_925154_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['exchange', 'last_updated'], name='stocks_stoc_exchang_e4ca00_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['current_price', 'last_updated'], name='stocks_stoc_current_5f7bd2_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['market_cap', 'last_updated'], name='stocks_stoc_market__da2818_idx'),
        ),
        migrations.AddField(
            model_name='usagestats',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_stats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billinghistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='usagestats',
            index=models.Index(fields=['user', '-date'], name='stocks_usag_user_id_18d9a2_idx'),
        ),
        migrations.AddIndex(
            model_name='usagestats',
            index=models.Index(fields=['date'], name='stocks_usag_date_89afef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usagestats',
            unique_together={('user', 'date')},
        ),
        migrations.AddIndex(
            model_name='notificationhistory',
            index=models.Index(fields=['user', '-created_at'], name='stocks_noti_user_id_d75fc5_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationhistory',
            index=models.Index(fields=['user', 'is_read'], name='stocks_noti_user_id_94fc47_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationhistory',
            index=models.Index(fields=['notification_type'], name='stocks_noti_notific_a2d2f0_idx'),
        ),
        migrations.AddIndex(
            model_name='billinghistory',
            index=models.Index(fields=['user', '-created_at'], name='stocks_bill_user_id_b98692_idx'),
        ),
        migrations.AddIndex(
            model_name='billinghistory',
            index=models.Index(fields=['invoice_id'], name='stocks_bill_invoice_43779c_idx'),
        ),
    ]
