# Generated by Django 5.2.6 on 2025-09-20 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0007_screener"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="alerts_limit",
            field=models.IntegerField(
                default=0, help_text="Email alerts limit per month"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="alerts_sent",
            field=models.IntegerField(default=0, help_text="Alerts sent this month"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="api_calls_used",
            field=models.IntegerField(default=0, help_text="API calls used this month"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="portfolios_limit",
            field=models.IntegerField(
                default=1, help_text="Number of portfolios allowed"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="screeners_limit",
            field=models.IntegerField(
                default=1, help_text="Number of screeners allowed"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="usage_reset_date",
            field=models.DateTimeField(
                blank=True, help_text="When usage counters were last reset", null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="watchlists_limit",
            field=models.IntegerField(
                default=1, help_text="Number of watchlists allowed"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="api_calls_limit",
            field=models.IntegerField(
                default=30, help_text="API calls limit per month"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="plan_name",
            field=models.CharField(
                default="Free Plan",
                help_text="Display name of current plan",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="plan_type",
            field=models.CharField(
                choices=[
                    ("free", "Free Plan"),
                    ("bronze", "Bronze Plan"),
                    ("silver", "Silver Plan"),
                    ("gold", "Gold Plan"),
                ],
                default="free",
                help_text="Current subscription plan",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="APICallLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "endpoint",
                    models.CharField(help_text="API endpoint called", max_length=200),
                ),
                (
                    "endpoint_type",
                    models.CharField(
                        choices=[
                            ("stocks_list", "List All Stocks"),
                            ("stock_detail", "Individual Stock"),
                            ("screener_run", "Run Screener"),
                            ("alert_create", "Create Alert"),
                            ("market_data", "Market Page Load"),
                            ("watchlist_create", "Create Watchlist"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "call_count",
                    models.IntegerField(
                        default=1, help_text="Number of API calls this action counts as"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("request_method", models.CharField(default="GET", max_length=10)),
                ("response_status", models.IntegerField(blank=True, null=True)),
                (
                    "response_time_ms",
                    models.IntegerField(
                        blank=True, help_text="Response time in milliseconds", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_calls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="stocks_apic_user_id_2b7552_idx",
                    ),
                    models.Index(
                        fields=["endpoint_type", "-created_at"],
                        name="stocks_apic_endpoin_24f73d_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="stocks_apic_created_df9b78_idx"
                    ),
                    models.Index(
                        fields=["user", "endpoint_type"],
                        name="stocks_apic_user_id_483476_idx",
                    ),
                ],
            },
        ),
    ]
