# Generated by Django 4.2.27 on 2025-12-02 14:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("fundamentals", "Trading Fundamentals"),
                            ("technical", "Technical Analysis"),
                            ("fundamental", "Fundamental Analysis"),
                            ("strategy", "Strategy Development"),
                            ("psychology", "Psychology & Risk Management"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("description", models.TextField()),
                ("thumbnail_url", models.URLField(blank=True, null=True)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(help_text="Total course duration in minutes"),
                ),
                ("order", models.IntegerField(default=0, help_text="Display order")),
                ("is_published", models.BooleanField(default=False)),
                (
                    "is_premium",
                    models.BooleanField(
                        default=False, help_text="Requires Premium subscription"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="GlossaryTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("technical", "Technical Analysis"),
                            ("fundamental", "Fundamental Analysis"),
                            ("order_types", "Order Types"),
                            ("market_structure", "Market Structure"),
                            ("risk_management", "Risk Management"),
                            ("psychology", "Trading Psychology"),
                            ("options", "Options & Derivatives"),
                            ("general", "General Trading"),
                        ],
                        max_length=20,
                    ),
                ),
                ("definition", models.TextField(help_text="Clear, concise definition")),
                (
                    "example",
                    models.TextField(
                        blank=True, help_text="Practical example or usage"
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                ("view_count", models.IntegerField(default=0)),
                ("tooltip_hover_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "related_terms",
                    models.ManyToManyField(blank=True, to="education.glossaryterm"),
                ),
            ],
            options={
                "verbose_name": "Glossary Term",
                "verbose_name_plural": "Glossary Terms",
                "ordering": ["term"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("video", "Video Tutorial"),
                            ("text", "Text Content"),
                            ("interactive", "Interactive Demo"),
                            ("mixed", "Mixed Content"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(help_text="Markdown formatted content")),
                (
                    "video_url",
                    models.URLField(
                        blank=True, help_text="YouTube or Vimeo URL", null=True
                    ),
                ),
                (
                    "interactive_demo",
                    models.JSONField(
                        blank=True,
                        help_text="Chart examples, interactive widgets configuration",
                        null=True,
                    ),
                ),
                (
                    "quiz_questions",
                    models.JSONField(
                        blank=True,
                        help_text='\n        Format: [\n            {\n                "question": "What is RSI?",\n                "options": ["A", "B", "C", "D"],\n                "correct": 0,\n                "explanation": "..."\n            }\n        ]\n        ',
                        null=True,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "duration_minutes",
                    models.IntegerField(help_text="Estimated completion time"),
                ),
                (
                    "key_takeaways",
                    models.JSONField(
                        blank=True,
                        help_text="List of 3-5 key points from lesson",
                        null=True,
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("is_premium", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="education.course",
                    ),
                ),
                (
                    "related_terms",
                    models.ManyToManyField(blank=True, to="education.glossaryterm"),
                ),
            ],
            options={
                "verbose_name": "Lesson",
                "verbose_name_plural": "Lessons",
                "ordering": ["course", "order"],
            },
        ),
        migrations.CreateModel(
            name="UserLearningStreak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_streak",
                    models.IntegerField(
                        default=0, help_text="Current consecutive days"
                    ),
                ),
                (
                    "longest_streak",
                    models.IntegerField(default=0, help_text="Longest streak ever"),
                ),
                ("last_activity_date", models.DateField(blank=True, null=True)),
                ("total_lessons_completed", models.IntegerField(default=0)),
                (
                    "total_time_spent_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_streak",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Learning Streak",
                "verbose_name_plural": "Learning Streaks",
            },
        ),
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                (
                    "quiz_score",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "time_spent_seconds",
                    models.IntegerField(
                        default=0, help_text="Time spent on lesson in seconds"
                    ),
                ),
                ("quiz_attempts", models.IntegerField(default=0)),
                (
                    "quiz_answers",
                    models.JSONField(
                        blank=True, help_text="User's quiz answers", null=True
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_accessed", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="education.lesson",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Progress",
                "verbose_name_plural": "User Progress Records",
                "ordering": ["-last_accessed"],
                "unique_together": {("user", "lesson")},
            },
        ),
        migrations.CreateModel(
            name="CourseCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_id",
                    models.CharField(blank=True, max_length=100, unique=True),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completion_time_hours",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "average_quiz_score",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="education.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificate",
                "verbose_name_plural": "Certificates",
                "unique_together": {("user", "course")},
            },
        ),
    ]
