#!/usr/bin/env bash
set -euo pipefail

# Secure XAMPP Database Setup (Linux)
# Usage: ./setup_xampp_db_secure.sh [DB_NAME] [DB_USER] [DB_PASSWORD] [MYSQL_ROOT_PASSWORD]
# If not provided, defaults are used and root is assumed to have no password.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DB_NAME="${1:-stockscanner}"
DB_USER="${2:-stockscanner_user}"
DB_PASSWORD="${3:-StockScanner_2025!}"
MYSQL_ROOT_PASSWORD="${4:-}"

# Try to find mysql client (XAMPP default path or system)
MYSQL_BIN="mysql"
if [ -x "/opt/lampp/bin/mysql" ]; then
  MYSQL_BIN="/opt/lampp/bin/mysql"
fi

echo "========================================"
echo "Secure XAMPP Database Setup (Linux)"
echo "========================================"
echo "DB_NAME     = ${DB_NAME}"
echo "DB_USER     = ${DB_USER}"
echo "DB_PASSWORD = [hidden]"
echo "MYSQL_BIN   = ${MYSQL_BIN}"

# Build root password flag
ROOT_FLAG=()
if [ -n "${MYSQL_ROOT_PASSWORD}" ]; then
  ROOT_FLAG=(-p"${MYSQL_ROOT_PASSWORD}")
fi

# Test root connection
echo "[STEP] Testing MySQL root connection..."
if ! "${MYSQL_BIN}" -u root "${ROOT_FLAG[@]}" -e "SELECT VERSION();" >/dev/null 2>&1; then
  echo "[ERROR] Could not connect to MySQL as root. If your root has a password, run:"
  echo "  ./setup_xampp_db_secure.sh ${DB_NAME} ${DB_USER} '<DB_PASSWORD>' '<MYSQL_ROOT_PASSWORD>'"
  exit 1
fi

echo "[OK] Root connection successful"

# Create DB and user
SQL=$(cat <<SQL
CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '${DB_USER}'@'localhost' IDENTIFIED BY '${DB_PASSWORD}';
GRANT ALL PRIVILEGES ON \`${DB_NAME}\`.* TO '${DB_USER}'@'localhost';
FLUSH PRIVILEGES;
SQL
)

echo "[STEP] Creating database and user..."
if ! "${MYSQL_BIN}" -u root "${ROOT_FLAG[@]}" -e "${SQL}" >/dev/null; then
  echo "[ERROR] Failed to create database/user or grant privileges."
  exit 1
fi

echo "[OK] Database and user configured"

# Update .env in place
ENV_FILE="${SCRIPT_DIR}/.env"
echo "[STEP] Updating ${ENV_FILE} with DB settings..."

# Create file if it doesn't exist
if [ ! -f "${ENV_FILE}" ]; then
  echo "# Generated by setup_xampp_db_secure.sh" >"${ENV_FILE}"
fi

# Remove existing keys and append new ones
for key in DB_ENGINE DB_NAME DB_USER DB_PASSWORD DB_HOST DB_PORT; do
  if grep -qE "^${key}=" "${ENV_FILE}"; then
    # delete matching line(s)
    sed -i.bak "/^${key}=.*/d" "${ENV_FILE}"
  fi
done

cat >>"${ENV_FILE}" <<ENV
DB_ENGINE=django.db.backends.mysql
DB_NAME=${DB_NAME}
DB_USER=${DB_USER}
DB_PASSWORD=${DB_PASSWORD}
DB_HOST=127.0.0.1
DB_PORT=3306
ENV

echo "[OK] .env updated"

echo
echo "========================================"
echo "Setup complete"
echo "========================================"
echo "- Database: ${DB_NAME}"
echo "- User: ${DB_USER}"
echo "- Password: [hidden]"
echo
echo "Next steps:"
echo "  1. Ensure XAMPP MySQL is running (sudo /opt/lampp/lampp startmysql)"
echo "  2. From this folder, run:  python create_database.py  (runs migrations)"
echo "  3. Start server:          python manage.py runserver"