# Generated by Django 4.2.11 on 2025-07-26 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic - $15'), ('pro', 'Pro - $30'), ('enterprise', 'Enterprise - $100')], default='free', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('company_name', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('exchange', models.CharField(default='NASDAQ', max_length=50)),
                ('current_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('price_change_today', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('price_change_week', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('price_change_month', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('price_change_year', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('change_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('bid_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('ask_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('bid_ask_spread', models.CharField(blank=True, max_length=50)),
                ('days_range', models.CharField(blank=True, max_length=50)),
                ('days_low', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('days_high', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('volume_today', models.BigIntegerField(blank=True, null=True)),
                ('avg_volume_3mon', models.BigIntegerField(blank=True, null=True)),
                ('dvav', models.DecimalField(blank=True, decimal_places=4, help_text='Day Volume Over Average Volume', max_digits=8, null=True)),
                ('shares_available', models.BigIntegerField(blank=True, null=True)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('market_cap_change_3mon', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('pe_ratio', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('pe_change_3mon', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('dividend_yield', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('one_year_target', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('week_52_low', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('week_52_high', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('earnings_per_share', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('book_value', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('price_to_book', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
            ],
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('price_above', 'Price Above'), ('price_below', 'Price Below'), ('volume_surge', 'Volume Surge'), ('price_change', 'Price Change %')], max_length=20)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['ticker'], name='stocks_stoc_ticker_5df4c9_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['market_cap'], name='stocks_stoc_market__c2c37a_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['current_price'], name='stocks_stoc_current_566855_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['volume'], name='stocks_stoc_volume_e22343_idx'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
