# Generated by Django migration fixer - Windows Production

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, help_text='Stock ticker symbol (e.g., AAPL)', max_length=10)),
                ('target_price', models.DecimalField(decimal_places=2, help_text='Target price for alert', max_digits=10)),
                ('alert_type', models.CharField(choices=[('above', 'Above Target'), ('below', 'Below Target')], help_text='Alert when price goes above or below target', max_length=5)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this alert is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('triggered_at', models.DateTimeField(blank=True, help_text='When the alert was triggered', null=True)),
                ('sent', models.BooleanField(default=False, help_text='Whether notification has been sent')),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('price_change_today', models.FloatField(blank=True, help_text='Price change from previous close', null=True)),
                ('price_change_percent', models.FloatField(blank=True, help_text='Percentage change from previous close', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Alert',
                'verbose_name_plural': 'Stock Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.CharField(choices=[('free', 'Free - $0/month'), ('basic', 'Basic - $9.99/month'), ('professional', 'Professional - $29.99/month'), ('expert', 'Expert - $49.99/month')], default='free', help_text='User membership level', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_customer_id', models.CharField(blank=True, help_text='Stripe customer ID for billing', max_length=255)),
                ('stripe_subscription_id', models.CharField(blank=True, help_text='Stripe subscription ID', max_length=255)),
                ('subscription_status', models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('past_due', 'Past Due'), ('unpaid', 'Unpaid')], default='active', help_text='Subscription status', max_length=20)),
                ('next_billing_date', models.DateField(blank=True, help_text='Next billing date', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Membership',
                'verbose_name_plural': 'User Memberships',
            },
        ),
        migrations.CreateModel(
            name='APIUsageTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(db_index=True, max_length=200)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('response_time_ms', models.IntegerField(help_text='Response time in milliseconds')),
                ('status_code', models.IntegerField()),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('request_size_bytes', models.IntegerField(default=0)),
                ('response_size_bytes', models.IntegerField(default=0)),
                ('membership_tier', models.CharField(db_index=True, max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Usage Tracking',
                'verbose_name_plural': 'API Usage Tracking',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['symbol', 'user'], name='stocks_stockalert_symbol_user_idx'),
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['-created_at'], name='stocks_stockalert_created_idx'),
        ),
        migrations.AddIndex(
            model_name='apiusagetracking',
            index=models.Index(fields=['endpoint', 'timestamp'], name='stocks_apiusage_endpoint_time_idx'),
        ),
        migrations.AddIndex(
            model_name='apiusagetracking',
            index=models.Index(fields=['user', 'timestamp'], name='stocks_apiusage_user_time_idx'),
        ),
    ]
