# Generated by Django 4.2.24 on 2025-09-05 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = []
