name: Backend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'Django/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'Django/**'

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: stockscanner
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -h 127.0.0.1 -proot"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: Django
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_production.txt

      - name: Django checks and migrations
        working-directory: Django
        env:
          DB_ENGINE: django.db.backends.mysql
          DB_NAME: stockscanner
          DB_USER: root
          DB_PASSWORD: root
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1
        run: |
          python manage.py check --deploy || true
          python manage.py migrate --noinput

      - name: Run tests (if present)
        working-directory: Django
        env:
          DB_ENGINE: django.db.backends.mysql
          DB_NAME: stockscanner
          DB_USER: root
          DB_PASSWORD: root
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
        run: |
          python -m pytest -q || echo "No tests or tests failing; continue for CI baseline"