name: Security Scan

on:
  push:
    branches: [ main, main-2.1 ]
  schedule:
    - cron: '0 3 * * *'

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image
        run: |
          docker build -t rts-backend:scan ./backend || echo "build failed, scanning fs only"
      - name: Run Trivy on image
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: rts-backend:scan
          format: table
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
        continue-on-error: true
      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: table
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'

  pip-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install pip-audit
        run: |
          python -m pip install --upgrade pip
          pip install pip-audit
      - name: Audit backend requirements
        run: |
          pip-audit -r backend/requirements.txt || true